import {file,texto,inteiro} from './comum.js';
import {canvas,codificar} from './imagem-base.js';
let libPromise;
export async function pdfLib(){if(globalThis.PDFLib)return globalThis.PDFLib;if(!libPromise)libPromise=new Promise((resolve,reject)=>{if(typeof document==='undefined'){reject(Error('Abra esta ferramenta no navegador para processar PDF.'));return;}const s=document.createElement('script');s.src=new URL('../../../recursos/bibliotecas/pdf-lib.min.js',import.meta.url).href;s.onload=()=>globalThis.PDFLib?resolve(globalThis.PDFLib):reject(Error('Biblioteca PDF não carregou.'));s.onerror=()=>{s.remove();libPromise=null;reject(Error('Não foi possível carregar a biblioteca PDF local.'));};document.head.append(s);});return libPromise;}
export async function lerPDF(f){file({arquivo:f},'arquivo',50*1024*1024);const lib=await pdfLib();let doc;try{doc=await lib.PDFDocument.load(await f.arrayBuffer(),{updateMetadata:false});}catch{throw Error('PDF inválido, danificado ou protegido por senha. Use uma cópia sem senha.');}if(doc.getPageCount()>1000)throw Error('Limite de 1.000 páginas por PDF.');return doc;}
export function paginas(s,total){s=String(s??'').trim();if(!s||s.toLowerCase()==='todas')return Array.from({length:total},(_,i)=>i);if(s.length>10000)throw Error('Lista de páginas muito longa.');const out=[];for(const part of s.split(',')){const m=/^\s*(\d+)\s*(?:-\s*(\d+))?\s*$/.exec(part);if(!m)throw Error('Páginas: use 1,3,5-8 ou todas.');const a=Number(m[1]),b=m[2]?Number(m[2]):a;if(a<1||b<a||b>total)throw Error('Intervalo fora do PDF (1 a '+total+').');for(let i=a;i<=b;i++)out.push(i-1);if(out.length>1000)throw Error('Limite de 1.000 páginas.');}if(new Set(out).size!==out.length)throw Error('Não repita páginas na seleção.');return out;}
export async function salvarPDF(doc,nome='documento.pdf',linhas=[]){const bytes=await doc.save();return {resumo:doc.getPageCount()+' páginas',linhas:['Processado localmente. Links, anexos e assinaturas devem ser conferidos no arquivo resultante; edição pode invalidar assinaturas.',...linhas],arquivo:{nome,blob:new Blob([bytes],{type:'application/pdf'})}};}
export async function pdfJS(f){file({arquivo:f},'arquivo',50*1024*1024);const m=await import(new URL('../../../recursos/bibliotecas/pdf.mjs',import.meta.url).href);m.GlobalWorkerOptions.workerSrc=new URL('../../../recursos/bibliotecas/pdf.worker.mjs',import.meta.url).href;try{return await m.getDocument({data:new Uint8Array(await f.arrayBuffer()),isEvalSupported:false,cMapUrl:new URL('../../../recursos/bibliotecas/cmaps/',import.meta.url).href,cMapPacked:true,standardFontDataUrl:new URL('../../../recursos/bibliotecas/standard_fonts/',import.meta.url).href,wasmUrl:new URL('../../../recursos/bibliotecas/wasm/',import.meta.url).href,iccUrl:new URL('../../../recursos/bibliotecas/iccs/',import.meta.url).href}).promise;}catch{throw Error('Não foi possível abrir o PDF; confira integridade e senha.');}}
export async function previewPDF(blob,indices){const doc=await pdfJS(blob);try{const chosen=indices.slice(0,12),c=canvas(3*220,Math.ceil(chosen.length/3)*310),ctx=c.getContext('2d');ctx.fillStyle='#eae6e0';ctx.fillRect(0,0,c.width,c.height);for(let i=0;i<chosen.length;i++){const page=await doc.getPage(chosen[i]+1),base=page.getViewport({scale:1}),vp=page.getViewport({scale:Math.min(200/base.width,280/base.height)}),pc=canvas(vp.width,vp.height);await page.render({canvasContext:pc.getContext('2d'),viewport:vp,background:'white'}).promise;const x=(i%3)*220+10,y=Math.floor(i/3)*310+10;ctx.drawImage(pc,x,y);ctx.fillStyle='#222';ctx.font='12px Arial';ctx.fillText('Página '+(chosen[i]+1),x,y+293);page.cleanup();pc.width=pc.height=1;}return await codificar(c);}finally{await doc.loadingTask.destroy();}}



