import {n,fmt} from './comum.js';
const mostrar=ms=>{const s=Math.floor(Math.max(0,ms)/1000);return String(Math.floor(s/3600)).padStart(2,'0')+':'+String(Math.floor(s/60)%60).padStart(2,'0')+':'+String(s%60).padStart(2,'0')+'.'+String(Math.floor(Math.max(0,ms)%1000/10)).padStart(2,'0');};
export function montarRelogio(el,foco=false){const section=document.createElement('section');section.className='relogio-local';const output=document.createElement('output');output.style.cssText='display:block;font-variant-numeric:tabular-nums;font-size:2.5rem;margin:1rem 0';output.setAttribute('aria-live','off');const status=document.createElement('p');status.setAttribute('aria-live','polite');const row=document.createElement('div'),laps=document.createElement('ol');let ativo=false,inicio=0,acumulado=0,fase='foco',duracao=25*60000,ultimo=0;
const inputs={};if(foco)for(const [key,label,valor]of [['foco','Foco (minutos)',25],['pausa','Pausa (minutos)',5]]){const wrap=document.createElement('label'),input=document.createElement('input');input.type='number';input.min='1';input.max='180';input.value=valor;wrap.textContent=label+' ';wrap.append(input);section.append(wrap);inputs[key]=input;}
const decorrido=()=>acumulado+(ativo?performance.now()-inicio:0);
const btn=(nome,fn)=>{const b=document.createElement('button');b.type='button';b.textContent=nome;b.addEventListener('click',fn);row.append(b);return b;};
const iniciar=btn('Iniciar',()=>{try{if(foco&&acumulado===0){duracao=n({minutos:inputs[fase].value},'minutos',1,180)*60000;for(const x of Object.values(inputs))x.disabled=true;}if(!ativo){inicio=performance.now();ativo=true;iniciar.disabled=true;status.textContent=foco?'Etapa: '+fase:'Cronômetro em andamento.';}}catch(e){status.textContent=e.message;}});
btn('Pausar',()=>{if(ativo){acumulado=decorrido();ativo=false;iniciar.disabled=false;status.textContent='Pausado.';}});
btn('Reiniciar',()=>{ativo=false;acumulado=0;ultimo=0;fase='foco';duracao=foco?Number(inputs.foco.value||25)*60000:0;iniciar.disabled=false;laps.replaceChildren();for(const x of Object.values(inputs))x.disabled=false;status.textContent='Pronto para iniciar.';render();});
if(!foco)btn('Marcar volta',()=>{if(!ativo&&acumulado===0)return;const t=decorrido(),li=document.createElement('li');li.textContent='Volta '+(laps.childElementCount+1)+': '+mostrar(t-ultimo)+' — total '+mostrar(t);laps.append(li);ultimo=t;});
function render(){const t=decorrido();output.textContent=mostrar(foco?duracao-t:t);if(foco&&ativo&&t>=duracao){ativo=false;acumulado=0;iniciar.disabled=false;const anterior=fase;fase=fase==='foco'?'pausa':'foco';status.textContent='Etapa de '+anterior+' concluída. Clique em Iniciar para '+fase+'.';duracao=Number(inputs[fase].value)*60000;for(const x of Object.values(inputs))x.disabled=false;}}
section.append(output,status,row,laps);el.append(section);render();const timer=setInterval(render,50);return ()=>{clearInterval(timer);section.remove();};}

