import {file,n,opcao,texto,fmt} from './comum.js';
const MAX_PIXELS=24000000,MAX_CANVAS=16000000;
export function dimensoesCabecalho(buffer){const u=new Uint8Array(buffer),v=new DataView(buffer);if(u.length>=24&&u[0]===137&&u[1]===80&&u[2]===78&&u[3]===71)return [v.getUint32(16),v.getUint32(20),'png'];if(u[0]===255&&u[1]===216){let p=2;while(p+8<u.length){if(u[p]!==255){p++;continue;}let marker=u[p+1];if(marker===0xD9||marker===0xDA)break;if(marker===0xD8||marker===0x01){p+=2;continue;}const len=v.getUint16(p+2);if(len<2)break;if([0xC0,0xC1,0xC2,0xC3,0xC5,0xC6,0xC7,0xC9,0xCA,0xCB,0xCD,0xCE,0xCF].includes(marker))return [v.getUint16(p+7),v.getUint16(p+5),'jpeg'];p+=2+len;}}
if(u.length>=30&&String.fromCharCode(...u.slice(0,4))==='RIFF'&&String.fromCharCode(...u.slice(8,12))==='WEBP'){const kind=String.fromCharCode(...u.slice(12,16));if(kind==='VP8X')return [1+u[24]+(u[25]<<8)+(u[26]<<16),1+u[27]+(u[28]<<8)+(u[29]<<16),'webp'];if(kind==='VP8 '&&u[23]===0x9d&&u[24]===0x01&&u[25]===0x2a)return [v.getUint16(26,true)&0x3fff,v.getUint16(28,true)&0x3fff,'webp'];if(kind==='VP8L'&&u[20]===0x2f){const b=v.getUint32(21,true);return [(b&0x3fff)+1,((b>>>14)&0x3fff)+1,'webp'];}}
throw Error('Formato não reconhecido. Use PNG, JPEG ou WebP válido.');}
export async function carregarImagem(f){file({arquivo:f});const buffer=await f.arrayBuffer(),[w,h]=dimensoesCabecalho(buffer);if(!w||!h||w*h>MAX_PIXELS||w>16000||h>16000)throw Error('Imagem grande demais: até 24 megapixels e 16 mil pixels por lado.');try{return await createImageBitmap(new Blob([buffer],{type:f.type}),{imageOrientation:'from-image'});}catch{throw Error('Não foi possível decodificar a imagem neste navegador.');}}
export function canvas(w,h){w=Math.round(w);h=Math.round(h);if(w<1||h<1||w>8192||h>8192||w*h>MAX_CANVAS)throw Error('Saída deve ter até 16 megapixels e 8.192 pixels por lado.');const c=document.createElement('canvas');c.width=w;c.height=h;return c;}
export function cor(v){if(!/^#[0-9a-f]{6}$/i.test(String(v)))throw Error('Cor inválida. Use #RRGGBB.');return v;}
export async function codificar(c,mime='image/png',q=.9){const b=await new Promise(r=>c.toBlob(r,mime,q));if(!b)throw Error('O navegador não conseguiu exportar a imagem.');if(b.type!==mime)throw Error('Este navegador não suporta exportar '+mime+'.');return b;}
export const tipo=d=>({'png':'image/png','jpeg':'image/jpeg','webp':'image/webp'}[opcao(d,'formato',['png','jpeg','webp'])]);
export async function resultadoImagem(c,mime='image/png',q=.9,antes=0,linhas=[]){const b=await codificar(c,mime,q),ext=mime.split('/')[1];return {resumo:c.width+' × '+c.height+' pixels',linhas:[fmt(b.size/1024)+' KB exportados',...(antes?[fmt(antes/1024)+' KB originais; variação '+fmt((b.size/antes-1)*100)+'%']:[]),...linhas],imagem:b,arquivo:{nome:'imagem.'+ext,blob:b}};}
export async function comImagem(d,fn){const f=file(d),im=await carregarImagem(f);try{return await fn(im,f);}finally{im.close();}}
export function temExif(buffer){const u=new Uint8Array(buffer),v=new DataView(buffer);if(u[0]!==255||u[1]!==216)return false;let p=2;while(p+4<u.length){if(u[p]!==255){p++;continue;}const m=u[p+1];if(m===0xda||m===0xd9)break;const len=v.getUint16(p+2);if(len<2)break;if(m===0xe1&&u[p+4]===69&&u[p+5]===120&&u[p+6]===105&&u[p+7]===102)return true;p+=len+2;}return false;}

