// Cadastro central dos seis produtos: pasta, porta local, marca provisória e cores-base.
// Marcas são provisórias; conferir conflito de marca e domínio antes de publicar.

export const produtos = [
  {
    número: 1,
    pasta: '1. Ferramentas para confeitaria',
    pacote: 'ferramentas-para-confeitaria',
    porta: 4311,
    marca: 'Doce Ofício',
    marcaDestaque: 'Ofício',
    prefixo: 'doce-ofício',
    descrição: 'Ferramentas gratuitas para confeitaria: custo da receita, preço de venda, ajuste de quantidades, lista de compras e orçamento.',
    identidade: {
      fundo: '#f8eee3',
      neutra: '#8f7b72',
      destaque: '#b85c6b',
      secundária: '#8f2d4a',
      destaques: { morango: '#c8434d', framboesa: '#a8325f', amora: '#6c3a6e', caramelo: '#b06a2e', pistache: '#6c8a45' },
    },
    ícones: ['cake', 'cake-slice', 'cookie', 'chef-hat', 'shopping-basket', 'receipt', 'scale', 'percent', 'cooking-pot', 'package'],
  },
  {
    número: 2,
    pasta: '2. Atividades escolares para imprimir',
    pacote: 'atividades-escolares-para-imprimir',
    porta: 4312,
    marca: 'Folha Pronta',
    marcaDestaque: 'Pronta',
    prefixo: 'folha-pronta',
    descrição: 'Geradores gratuitos de atividades escolares para imprimir: operações, tabuada, caça-palavras e caligrafia, com gabarito.',
    identidade: {
      fundo: '#f7f4ec',
      neutra: '#7f7a70',
      destaque: '#4d78b8',
      secundária: '#d99a1e',
      destaques: { céu: '#3f86c4', girassol: '#c98a12', lápis: '#c8613a', folha: '#3f8f5f', lilás: '#7b64b0' },
    },
    ícones: ['book-open', 'pencil-line', 'grid-3x3', 'x', 'divide', 'sigma', 'type', 'file-text', 'shuffle', 'eye'],
  },
  {
    número: 3,
    pasta: '3. Ferramentas para crochê e artesanato',
    pacote: 'ferramentas-para-croche-e-artesanato',
    porta: 4313,
    marca: 'Ponto e Preço',
    marcaDestaque: 'Preço',
    prefixo: 'ponto-e-preço',
    descrição: 'Ferramentas gratuitas para crochê e artesanato: preço da peça, valor da hora, custo do fio, encomendas e orçamento.',
    identidade: {
      fundo: '#f4eee4',
      neutra: '#857a74',
      destaque: '#8872bf',
      secundária: '#7c3868',
      destaques: { lavanda: '#7f69b8', ameixa: '#8a3a70', malva: '#b0607e', musgo: '#6a7a46', anil: '#4d6aa8' },
    },
    ícones: ['scissors', 'spool', 'hourglass', 'calendar-days', 'receipt', 'tag', 'ruler', 'boxes', 'percent'],
  },
  {
    número: 4,
    pasta: '4. Planejamento de churrasco e festas',
    pacote: 'planejamento-de-churrasco-e-festas',
    porta: 4314,
    marca: 'Mesa Farta',
    marcaDestaque: 'Farta',
    prefixo: 'mesa-farta',
    descrição: 'Planejadores gratuitos de churrasco, festa infantil e almoço: quantidades, lista de compras, orçamento e divisão de despesas.',
    identidade: {
      fundo: '#fbf0e6',
      neutra: '#8c7b70',
      destaque: '#df6a52',
      secundária: '#5f9670',
      destaques: { brasa: '#c9502e', coral: '#e0664f', limão: '#8a9a2c', verde: '#4f9466', céu: '#4a8ac0' },
    },
    ícones: ['flame', 'party-popper', 'utensils', 'cup-soda', 'users', 'shopping-cart', 'wallet', 'calendar-clock', 'beef', 'salad'],
  },
  {
    número: 5,
    pasta: '5. Calculadoras de pintura e reforma',
    pacote: 'calculadoras-de-pintura-e-reforma',
    porta: 4315,
    marca: 'Demão Certa',
    marcaDestaque: 'Certa',
    prefixo: 'demão-certa',
    descrição: 'Calculadoras gratuitas de pintura e reforma: área de paredes, quantidade de tinta, piso por caixa, rodapé e orçamento estimado.',
    identidade: {
      fundo: '#f3ece0',
      neutra: '#857c70',
      destaque: '#6f9078',
      secundária: '#c06640',
      destaques: { sálvia: '#5f8a6c', terracota: '#c0603a', azulejo: '#3f7a8a', ocre: '#b08a2e', grafite: '#5c6773' },
    },
    ícones: ['paintbrush', 'paint-roller', 'paint-bucket', 'ruler', 'grid-2x2', 'square-dashed', 'door-open', 'app-window', 'receipt', 'layers'],
  },
  {
    número: 6,
    pasta: '6. Moldes de caixas e embalagens',
    pacote: 'moldes-de-caixas-e-embalagens',
    porta: 4316,
    marca: 'Dobra & Cola',
    marcaDestaque: 'Cola',
    prefixo: 'dobra-e-cola',
    descrição: 'Geradores gratuitos de moldes de caixas, caixa com tampa, envelope e etiquetas, com PDF e SVG em tamanho real.',
    identidade: {
      fundo: '#f5f0e7',
      neutra: '#827a70',
      destaque: '#1f6f7a',
      secundária: '#e08e55',
      destaques: { petróleo: '#1f6f7a', damasco: '#d9803f', kraft: '#9a6f45', menta: '#3f9480', ameixa: '#8a4a6e' },
    },
    ícones: ['package', 'package-open', 'box', 'mail', 'tag', 'ruler', 'scissors', 'file-down', 'square', 'layers'],
  },
];
