const tools=[
 {id:'orcamento',cat:'casa',icon:'◫',title:'Orçamento doméstico',desc:'Veja quanto sobra do mês e organize seus gastos.',type:'budget'},
 {id:'reforma',cat:'casa',icon:'⌂',title:'Calculadora de tinta',desc:'Estime litros de tinta para paredes e teto.',type:'paint'},
 {id:'festa',cat:'festa',icon:'✦',title:'Planejador de festa',desc:'Calcule bebidas, convidados e orçamento básico.',type:'party'},
 {id:'confeitaria',cat:'confeitaria',icon:'♨',title:'Preço de venda',desc:'Descubra um preço justo para sua receita.',type:'cake'},
 {id:'artesanato',cat:'artesanato',icon:'✿',title:'Custo do artesanato',desc:'Some material, tempo e margem sem esquecer nada.',type:'craft'},
 {id:'checklist',cat:'organização',icon:'☑',title:'Checklist personalizado',desc:'Monte uma lista simples para imprimir ou copiar.',type:'checklist'},
 {id:'compras',cat:'casa',icon:'⌁',title:'Preço por unidade',desc:'Compare embalagens e escolha o melhor custo.',type:'unit'},
 {id:'viagem',cat:'organização',icon:'⌖',title:'Custo de combustível',desc:'Estime o gasto da sua próxima viagem.',type:'fuel'},
 {id:'rateio',cat:'festa',icon:'÷',title:'Divisor de contas',desc:'Divida uma conta de forma clara e rápida.',type:'split'}
];
const $=id=>document.getElementById(id);const value=id=>$(id)?.value??0;const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);const num=v=>Number(String(v).replace(',','.'))||0;const escapeHTML=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const grid=$('toolGrid'),search=$('searchInput'),dialog=$('toolDialog'),body=$('dialogBody'),title=$('dialogTitle'),category=$('dialogCategory');
function render(){const term=(search.value||'').toLowerCase();const active=document.querySelector('.category.active')?.dataset.category||'todos';grid.innerHTML=tools.filter(t=>(active==='todos'||t.cat===active)&&(`${t.title} ${t.desc} ${t.cat}`.toLowerCase().includes(term))).map(t=>`<article class="tool-card"><div class="tool-icon">${t.icon}</div><h3>${t.title}</h3><p>${t.desc}</p><button data-tool="${t.id}">Abrir ferramenta →</button></article>`).join('')||'<p style="color:var(--muted)">Nenhuma ferramenta encontrada. Tente outro termo.</p>';grid.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>openTool(tools.find(t=>t.id===b.dataset.tool)));}
function field(label,name,value='',type='number',extra=''){return `<div class="form-field ${extra}"><label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" value="${value}" ${type==='number'?'min="0" step="any"':''}></div>`}
function openTool(tool){title.textContent=tool.title;category.textContent=tool.cat;let fields='';let action='Calcular resultado';if(tool.type==='budget')fields=field('Renda do mês (R$)','income','3000')+field('Gastos fixos (R$)','fixed','1400')+field('Outros gastos (R$)','other','600');if(tool.type==='paint')fields=field('Área das paredes (m²)','area','35')+field('Rendimento da tinta (m²/L)','yield','10')+field('Demãos','coats','2');if(tool.type==='party')fields=field('Convidados','guests','20')+field('Duração (horas)','hours','4')+field('Orçamento (R$)','partyBudget','500');if(tool.type==='cake')fields=field('Ingredientes (R$)','ingredients','42.50')+field('Horas de trabalho','hoursCake','3')+field('Valor da sua hora (R$)','hourValue','20')+field('Margem (%)','margin','30');if(tool.type==='craft')fields=field('Materiais (R$)','materials','35')+field('Horas de trabalho','hoursCraft','2')+field('Valor da sua hora (R$)','craftHour','18')+field('Margem (%)','craftMargin','30');if(tool.type==='unit')fields=field('Quantidade da embalagem A','qtyA','500')+field('Preço A (R$)','priceA','12')+field('Quantidade da embalagem B','qtyB','1000')+field('Preço B (R$)','priceB','20');if(tool.type==='fuel')fields=field('Distância total (km)','distance','300')+field('Consumo do carro (km/L)','consumption','12')+field('Preço do combustível (R$/L)','fuelPrice','6');if(tool.type==='split')fields=field('Valor total (R$)','total','600')+field('Número de pessoas','people','3');if(tool.type==='checklist'){fields='<div class="form-field full"><label for="items">Itens (um por linha)</label><textarea id="items" rows="7" placeholder="Ex.: Comprar ingredientes\nSeparar materiais\nConfirmar horário">Comprar ingredientes\nSeparar materiais\nConfirmar horário</textarea></div>';action='Gerar lista';}body.innerHTML=`<form id="toolForm"><div class="form-grid">${fields}</div><div class="dialog-actions"><button class="btn btn-primary" type="submit">${action} <span>→</span></button><button class="category" type="button" id="copyResult" style="display:none">Copiar resultado</button></div><div id="result" aria-live="polite"></div></form>`;dialog.showModal();$('toolForm').onsubmit=e=>{e.preventDefault();calculate(tool.type);};}
function calculate(type){const result=$('result');let main='',sub='',copySub='';if(type==='budget'){const r=num(value('income')),s=num(value('fixed'))+num(value('other')),v=r-s;main=money(v);sub=v>=0?'valor disponível depois dos gastos informados':'atenção: os gastos estão acima da renda';copySub=sub}if(type==='paint'){const liters=num(value('area'))*num(value('coats'))/Math.max(num(value('yield')),1);main=`${liters.toFixed(1)} L`;sub='estimativa de tinta para as demãos informadas';copySub=sub}if(type==='party'){const g=num(value('guests')),drink=g*num(value('hours'))*.4;main=`${Math.ceil(drink)} L`;sub=`aproximadamente ${Math.ceil(g*1.5)} kg de comida · ${money(num(value('partyBudget'))/Math.max(g,1))} por pessoa do orçamento`;copySub=sub}if(type==='cake'){const cost=num(value('ingredients'))+num(value('hoursCake'))*num(value('hourValue'));main=money(cost*(1+num(value('margin'))/100));sub='preço sugerido com custo e margem informados';copySub=sub}if(type==='craft'){const cost=num(value('materials'))+num(value('hoursCraft'))*num(value('craftHour'));main=money(cost*(1+num(value('craftMargin'))/100));sub='preço sugerido com material, tempo e margem';copySub=sub}if(type==='unit'){const a=num(value('priceA'))/(num(value('qtyA'))/1000),b=num(value('priceB'))/(num(value('qtyB'))/1000);main=`${money(Math.min(a,b))}/kg`;sub=a<b?'a embalagem A tem menor preço por kg':'a embalagem B tem menor preço por kg';copySub=sub}if(type==='fuel'){const liters=num(value('distance'))/Math.max(num(value('consumption')),.1);main=money(liters*num(value('fuelPrice')));sub=`aproximadamente ${liters.toFixed(1)} L para ${num(value('distance'))} km`;copySub=sub}if(type==='split'){const v=num(value('total'))/Math.max(num(value('people')),1);main=money(v);sub=`valor igual para cada uma das ${num(value('people'))} pessoas`;copySub=sub}if(type==='checklist'){const items=String(value('items')).split('\n').map(x=>x.trim()).filter(Boolean);main=`${items.length} itens`;copySub=items.map(x=>`☐ ${x}`).join(' | ');sub=items.map(x=>`☐ ${escapeHTML(x)}`).join('<br>')}result.innerHTML=`<div class="result-box"><small>seu resultado</small><strong>${main}</strong><span style="font-size:12px;color:var(--muted)">${sub}</span></div>`;const copy=$('copyResult');copy.style.display='inline-flex';copy.onclick=()=>{navigator.clipboard?.writeText(`${title.textContent}: ${main} — ${copySub}`);showToast('Resultado copiado!');};}
function showToast(text){const t=$('toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
document.querySelectorAll('.category').forEach(b=>b.onclick=()=>{if(!b.dataset.category)return;document.querySelectorAll('.category').forEach(x=>x.classList.remove('active'));b.classList.add('active');render();});search.oninput=render;$('closeDialog').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});$('themeToggle').onclick=()=>document.body.classList.toggle('dark');render();
