export const num=(v,label='Valor',min=0,max=1e9)=>{const s=String(v??'').trim();if(!/^[+-]?(?:\d+(?:[.,]\d+)?|[.,]\d+)$/.test(s))throw Error(`${label}: informe um número válido, sem separador de milhar.`);const n=Number(s.replace(',','.'));if(!Number.isFinite(n)||n<min||n>max)throw Error(`${label}: use um valor entre ${min} e ${max}.`);return n;};
export const positive=(v,l)=>num(v,l,Number.MIN_VALUE);
export const integer=(v,l,min=1,max=10000)=>{const n=num(v,l,min,max);if(!Number.isInteger(n))throw Error(`${l}: informe um inteiro.`);return n;};
export const fmt=n=>Number(n).toLocaleString('pt-BR',{maximumFractionDigits:4});
export const money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
export const field=(nome,rotulo,valor=0,min=0,max=1e9)=>({nome,rotulo,tipo:'number',valor,min,max,passo:'any',obrigatorio:true});
export const txt=(nome,rotulo,valor='')=>({nome,rotulo,tipo:'textarea',valor,obrigatorio:true});
export const select=(nome,rotulo,valor,values)=>({nome,rotulo,tipo:'select',valor,opcoes:values.map(v=>({valor:v,rotulo:v}))});
export const lines=v=>{const r=String(v??'').trim().split(/\r?\n/).map(s=>s.trim()).filter(Boolean);if(!r.length||r.length>200)throw Error('Informe de 1 a 200 linhas.');return r;};
export const rows=(v,count)=>lines(v).map((s,i)=>{const a=s.split(';').map(x=>x.trim());if(a.length!==count||a.some(x=>!x))throw Error(`Linha ${i+1}: use ${count} colunas separadas por ponto e vírgula.`);return a;});
export function result(resumo,linhas=[]){return {resumo,linhas,arquivo:{nome:'resultado.txt',blob:new Blob([[resumo,...linhas].join('\n')],{type:'text/plain;charset=utf-8'})}};}
export function sheet(title,body,extra=[],height=297){const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="210mm" height="${height}mm" viewBox="0 0 210 ${height}"><rect width="210" height="${height}" fill="white"/><g fill="#222" font-family="Arial,sans-serif"><text x="12" y="15" font-size="6">${esc(title)}</text>${body}</g></svg>`;return {...result(title,extra),svg,arquivo:{nome:'atividade.svg',blob:new Blob([svg],{type:'image/svg+xml'})}};}
export const textAt=(s,x,y,size=4)=>`<text x="${x}" y="${y}" font-size="${size}">${esc(s)}</text>`;
export const lineSvg=(x1,y1,x2,y2)=>`<path d="M${x1} ${y1}H${x2}" stroke="#aab0b8" stroke-width=".2"/>`;
export const paragraphs=(arr,start=30,gap=8)=>arr.map((s,i)=>textAt(s,12,start+i*gap)).join('');
export function price(cost,margin,tax){const m=num(margin,'Margem (%)',0,99.99),t=num(tax,'Taxas (%)',0,99.99);if(m+t>=100)throw Error('Margem e taxas somadas precisam ser menores que 100%.');return cost/(1-(m+t)/100);}
export function date(v){if(!/^\d{4}-\d{2}-\d{2}$/.test(v))throw Error('Informe uma data válida.');const d=new Date(v+'T12:00:00Z');if(!Number.isFinite(+d)||d.toISOString().slice(0,10)!==v)throw Error('Data inválida.');return d;}
export function tool(id,categoria,titulo,descricao,metodologia,campos,run){return {id,categoria,titulo,descricao,metodologia,campos,executar:async d=>{for(const campo of campos){if(campo.tipo==='number')num(d[campo.nome],campo.rotulo,campo.min??0,campo.max??1e9);if(campo.tipo==='select'&&!campo.opcoes.some(o=>o.valor===d[campo.nome]))throw Error(campo.rotulo+': selecione uma opção válida.');if(campo.obrigatorio&&campo.tipo==='textarea'&&(!String(d[campo.nome]??'').trim()||String(d[campo.nome]).length>30000))throw Error(campo.rotulo+': informe um texto de até 30.000 caracteres.');}const r=await run(d);if(!r||!r.resumo)throw Error('Não foi possível gerar o resultado.');return r;}};}
export function textBlock(s,x,y,width=84,size=3.5){const limit=Math.max(1,Math.floor(width/size)),parts=[];let current='';for(const word of String(s).split(/\s+/)){if((current+' '+word).trim().length<=limit){current=(current+' '+word).trim();continue;}if(current){parts.push(current);current='';}for(let offset=0;offset<word.length;offset+=limit){const chunk=word.slice(offset,offset+limit);if(offset+limit<word.length)parts.push(chunk);else current=chunk;}}if(current)parts.push(current);return parts.map((line,i)=>textAt(line,x,y+i*(size+1.5),size)).join('');}
