import {elemento,botao} from './elemento.js';
import {gerarPayloadPix} from './pix/gerar-payload-pix.js';
import {validarValorPix} from './pix/validar-valor-pix.js';
import {notificar} from './notificar.js';
import {baixar} from './baixar.js';
export function renderizarApoio(config){const alvo=document.getElementById('apoio-conteudo');alvo.replaceChildren();const apoio=config.apoio??{};
 if(!apoio.ativo||!apoio.chave||!apoio.nome||!apoio.cidade){alvo.append(elemento('h2','','Obrigado por estar aqui.'),elemento('p','','O apoio por Pix ainda não está disponível. Você já pode usar todas as ferramentas e compartilhar o projeto.'));return;}
 const form=elemento('form');const valores=elemento('div','pix-valores');const campo=elemento('div','campo');const label=elemento('label','','Valor do apoio (R$)');label.htmlFor='valor-pix';const entrada=elemento('input');entrada.id='valor-pix';entrada.inputMode='decimal';entrada.value='5,00';campo.append(label,entrada);const resultado=elemento('div');
 for(const valor of [1,5,10,20,30,50,100])valores.append(botao('R$ '+valor,()=>{entrada.value=valor+',00';resultado.replaceChildren();}));
 entrada.oninput=()=>resultado.replaceChildren();const gerar=elemento('button','botao primario','Revisar apoio');gerar.type='submit';form.append(valores,campo,gerar,resultado);alvo.append(form);
 form.onsubmit=e=>{e.preventDefault();resultado.replaceChildren();const valor=validarValorPix(entrada.value);if(!valor.válido){resultado.append(elemento('p','erro',valor.erro));return;}resultado.append(elemento('h3','',`R$ ${(valor.centavos/100).toFixed(2).replace('.',',')} para ${apoio.nome}`),elemento('p','',`Cidade: ${apoio.cidade}. Confira o recebedor novamente no seu banco.`),botao('Gerar QR Code Pix',async()=>{try{const payload=gerarPayloadPix({...apoio,centavos:valor.centavos});const {default:fabrica}=await import('../recursos/bibliotecas/qrcode.mjs');const qr=fabrica(0,'M');qr.addData(payload);qr.make();resultado.replaceChildren(elemento('h3','',`Apoio de R$ ${(valor.centavos/100).toFixed(2).replace('.',',')}`));const img=elemento('img','qr');img.alt='QR Code Pix para o valor e recebedor revisados';img.src=qr.createDataURL(6,24);const texto=elemento('textarea','nome-registro');texto.readOnly=true;texto.value=payload;texto.setAttribute('aria-label','Código Pix Copia e Cola');resultado.append(img,elemento('p','',apoio.nome+' · '+apoio.cidade),texto,botao('Copiar Pix',async()=>{try{await navigator.clipboard.writeText(payload);notificar('Código Pix copiado.');}catch{texto.select();notificar('Selecione e copie o código manualmente.');}}),botao('Baixar código',()=>baixar(new Blob([payload],{type:'text/plain'}),'pix-copia-e-cola.txt')),elemento('p','','Este portal não confirma pagamentos. A geração do código não realiza nenhum débito.'));}catch(e){resultado.append(elemento('p','erro',e.message));}}));};
}
