import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {transform} from 'esbuild';import crypto from 'node:crypto';
const raiz=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const destino=path.join(raiz,'publicacao');
if(path.dirname(destino)!==raiz||path.basename(destino)!=='publicacao')throw Error('Destino de build fora do portal.');
if(fs.existsSync(destino)){if(fs.lstatSync(destino).isSymbolicLink())throw Error('Destino do build não pode ser link.');fs.rmSync(destino,{recursive:true});}fs.mkdirSync(destino,{recursive:true});
for(const nome of ['index.html','estilos','scripts','recursos','configurações'])fs.cpSync(path.join(raiz,nome),path.join(destino,nome),{recursive:true});
const arquivos=[];function listar(p){for(const item of fs.readdirSync(p,{withFileTypes:true})){const f=path.join(p,item.name);if(item.isDirectory())listar(f);else arquivos.push(f);}}listar(destino);
for(const f of arquivos){if(f.includes(path.sep+'bibliotecas'+path.sep))continue;const ext=path.extname(f);if(['.js','.css'].includes(ext)){const {code}=await transform(fs.readFileSync(f,'utf8'),{loader:ext==='.css'?'css':'js',minify:true,target:'es2022',charset:'utf8'});fs.writeFileSync(f,code);}}
fs.writeFileSync(path.join(destino,'.htaccess'),`Options -Indexes\n<IfModule mod_headers.c>\nHeader always set X-Content-Type-Options "nosniff"\nHeader always set Referrer-Policy "no-referrer"\nHeader always set X-Frame-Options "DENY"\nHeader always set Content-Security-Policy "default-src 'self'; script-src 'self' 'wasm-unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self'; connect-src 'self'; worker-src 'self' blob:; object-src 'none'; base-uri 'self'; frame-ancestors 'none'"\n</IfModule>\nAddType text/javascript .mjs\nAddType font/woff2 .woff2\n`);
const configuracao=JSON.parse(fs.readFileSync(path.join(raiz,'configurações','publica.json'),'utf8'));const endereco=configuracao.publicacao?.enderecoBase;
fs.writeFileSync(path.join(destino,'robots.txt'),endereco?'User-agent: *\nAllow: /\n':'User-agent: *\nDisallow: /\n');
fs.writeFileSync(path.join(destino,'404.html'),'<!doctype html><html lang="pt-BR"><meta charset="utf-8"><title>Página não encontrada</title><h1>Página não encontrada</h1><p>Volte ao endereço inicial do Doce Ofício para encontrar suas ferramentas.</p></html>');
if(endereco){const url=new URL(endereco);if(url.protocol!=='https:')throw Error('Endereço de publicação deve usar HTTPS.');fs.writeFileSync(path.join(destino,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${url.href.replaceAll('&','&amp;').replaceAll('<','&lt;')}</loc></url></urlset>`);const html=fs.readFileSync(path.join(destino,'index.html'),'utf8');fs.writeFileSync(path.join(destino,'index.html'),html.replace('</head>',`<link rel="canonical" href="${url.href.replaceAll('&','&amp;').replaceAll('"','&quot;')}"></head>`));}
arquivos.length=0;listar(destino);const hashes=Object.fromEntries(arquivos.map(f=>[path.relative(destino,f).replaceAll('\\','/'),crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex')]));fs.writeFileSync(path.join(raiz,'manifesto-publicacao.json'),JSON.stringify(hashes,null,2));console.log(`Pacote criado: ${destino}; ${arquivos.length} arquivos, sem dependências do projeto original.`);
