import {elemento,botao} from './elemento.js';
import {ler,guardar} from './armazenamento.js';
import {notificar} from './notificar.js';

const chaveAvisos='mural-comunicados-v1',chaveBanners='mural-banners-v1',chaveRecentes='ferramentas-recentes-v1';
const avisosPadrao=[{id:'novidade-estudio',titulo:'Novo: estúdio de arquivos',texto:'Agora você pode posicionar o recorte e conferir a prévia antes de baixar.'},{id:'privacidade-local',titulo:'Arquivos no seu navegador',texto:'PDFs e imagens escolhidos nas ferramentas não são enviados pelo portal.'}];
const bannersPadrao=[{id:'estudio',titulo:'Seu arquivo, do seu jeito',texto:'Recorte imagens e PDFs com uma prévia visual antes de baixar.',imagem:'recursos/ilustracao-oficio.png',alvo:'#estudio'},{id:'catalogo',titulo:'Uma ajuda para cada plano',texto:'Pesquise entre 150 ferramentas organizadas por assunto.',imagem:'recursos/ilustracao-oficio.png',alvo:'#ferramentas'}];
const faq=[['Meus arquivos são enviados?','Não. As ferramentas de arquivo trabalham localmente no navegador. Ao ativar uma futura conta, a política deverá explicar claramente qualquer armazenamento opcional.'],['Por que aparece “processando”?','A interface confirma cada etapa e mantém um período mínimo de retorno visual para que você consiga acompanhar a ação. O processamento real pode terminar antes.'],['Onde ficam os meus salvos?','Nesta versão, registros de texto e preferências ficam somente no navegador. Arquivos selecionados não entram nos salvos locais.'],['Posso recuperar um download em outro computador?','Ainda não. O esquema de conta com Prisma está preparado, mas sincronização e login social só podem ser ativados com servidor, banco e credenciais do proprietário.'],['Como sei se o PDF ficou correto?','Use a prévia no Estúdio ou abra o arquivo baixado em um leitor de PDF. Revise conteúdo, margens e assinaturas, que podem perder validade após edição.']];
let indiceBanner=0,temporizadorBanner;
const $(id)=>document.getElementById(id);
function lista(chave,padrao){const valor=ler(chave,padrao);return Array.isArray(valor)&&valor.length?valor:padrao;}
function avisos(){return lista(chaveAvisos,avisosPadrao);}
function banners(){return lista(chaveBanners,bannersPadrao);}
function abrirDialogo(id){const d=$(id);if(!d.open)d.showModal();}
function renderizarAvisos(){const itens=avisos();$('comunicados-rolantes').textContent=itens.map(a=>`${a.titulo}: ${a.texto}`).join('  •  ');const listaAvisos=$('lista-comunicados');listaAvisos.replaceChildren(...itens.map(a=>{const item=elemento('article','aviso-completo');item.append(elemento('h3','',a.titulo),elemento('p','',a.texto));return item;}));}
function renderizarBanners(){const itens=banners();if(indiceBanner>=itens.length)indiceBanner=0;const b=itens[indiceBanner];const alvo=$('banner-principal');alvo.style.setProperty('--imagem-banner',`url("${b.imagem}")`);alvo.replaceChildren(elemento('span','sobretitulo','DESTAQUE'),elemento('h3','',b.titulo),elemento('p','',b.texto),Object.assign(elemento('a','botao secundario','Ver agora'),{href:b.alvo||'#inicio'}));$('banner-posicao').textContent=`${indiceBanner+1} de ${itens.length}`;
 const edicao=$('lista-banners-edicao');edicao.replaceChildren(...itens.map((item,i)=>{const linha=elemento('div','banner-item');linha.append(elemento('strong','',item.titulo),botao('Remover',()=>{if(!confirmarRemocao())return;const personalizados=banners().filter(x=>!bannersPadrao.some(p=>p.id===x.id));const alvoLocal=personalizados.findIndex(x=>x.id===item.id);if(alvoLocal<0){notificar('Os banners iniciais ficam como exemplo.');return;}personalizados.splice(alvoLocal,1);guardar(chaveBanners,[...bannersPadrao,...personalizados]);renderizarBanners();}));return linha;}));}
function confirmarRemocao(){return true;}
function trocarBanner(delta){indiceBanner=(indiceBanner+delta+banners().length)%banners().length;renderizarBanners();}
function iniciarBanner(){clearInterval(temporizadorBanner);temporizadorBanner=setInterval(()=>trocarBanner(1),30000);}
function renderizarFaq(){const alvo=$('lista-faq');alvo.replaceChildren(...faq.map(([pergunta,resposta])=>{const d=elemento('details','faq-item');d.append(elemento('summary','',pergunta),elemento('p','',resposta));return d;}));}
export function registrarRecente(f,categoria){if(f.sensivel)return;const anteriores=lista(chaveRecentes,[]).filter(x=>x.id!==f.id);const item={id:f.id,titulo:f.titulo,categoria:categoria.nome,cor:categoria.cor};guardar(chaveRecentes,[item,...anteriores].slice(0,6));renderizarRecentes();}
export function renderizarRecentes(abrir){const itens=lista(chaveRecentes,[]);const secao=$('recentes'),alvo=$('lista-recentes');if(!itens.length){secao.hidden=true;return;}secao.hidden=false;alvo.replaceChildren(...itens.map(item=>{const a=elemento('button','recente');a.style.setProperty('--destaque',item.cor);a.append(elemento('small','',item.categoria),elemento('strong','',item.titulo),elemento('span','','Abrir novamente'));a.onclick=()=>abrir?.(item.id);return a;}));}
function inicializarMenu(categorias){const gatilho=document.querySelector('.nav-menu-gatilho'),menu=$('menu-ferramentas'),alvo=$('menu-categorias');alvo.replaceChildren(...categorias.map(c=>{const a=elemento('a','',c.nome);a.href='#ferramentas';a.onclick=()=>{const seletor=$('categoria');seletor.value=c.id;seletor.dispatchEvent(new Event('change'));};return a;}));const alternar=aberto=>{menu.hidden=!aberto;gatilho.setAttribute('aria-expanded',String(aberto));};gatilho.onclick=()=>alternar(menu.hidden);gatilho.parentElement.onmouseleave=()=>alternar(false);gatilho.onkeydown=e=>{if(e.key==='Escape')alternar(false);};}
function inicializarModais(){document.querySelectorAll('[data-fechar]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog')?.close()));document.querySelectorAll('.abrir-login').forEach(b=>b.onclick=()=>abrirDialogo('login-dialogo'));$('abrir-comunicados').onclick=()=>abrirDialogo('comunicados-dialogo');$('editar-banners').onclick=()=>abrirDialogo('banners-dialogo');$('banner-anterior').onclick=()=>trocarBanner(-1);$('banner-proximo').onclick=()=>trocarBanner(1);
 $('form-comunicado').onsubmit=e=>{e.preventDefault();const dados=new FormData(e.currentTarget),titulo=String(dados.get('titulo')||'').trim(),texto=String(dados.get('texto')||'').trim();if(!titulo||!texto)return;const itens=[...avisos(),{id:crypto.randomUUID(),titulo,texto}].slice(-12);if(guardar(chaveAvisos,itens)){e.currentTarget.reset();renderizarAvisos();notificar('Aviso adicionado neste navegador.');}};
 $('form-banner').onsubmit=async e=>{e.preventDefault();const dados=new FormData(e.currentTarget),arquivo=dados.get('imagem');if(!(arquivo instanceof File)||arquivo.size>800000)throw Error('Escolha uma imagem de até 800 KB.');const imagem=await new Promise((resolve,reject)=>{const leitor=new FileReader();leitor.onload=()=>resolve(leitor.result);leitor.onerror=()=>reject(Error('Não foi possível ler a imagem.'));leitor.readAsDataURL(arquivo);});const item={id:crypto.randomUUID(),titulo:String(dados.get('titulo')).trim(),texto:String(dados.get('texto')).trim(),imagem,alvo:'#inicio'};const extras=banners().filter(x=>!bannersPadrao.some(p=>p.id===x.id));if(extras.length>=5){notificar('Limite de cinco banners pessoais.');return;}if(guardar(chaveBanners,[...bannersPadrao,...extras,item])){e.currentTarget.reset();indiceBanner=banners().length-1;renderizarBanners();notificar('Banner adicionado neste navegador.');}};
 if(!ler('boas-vindas-v2',false)){setTimeout(()=>{abrirDialogo('boas-vindas');guardar('boas-vindas-v2',true);},700);}
}
function revelarAoRolar(){const alvos=[...document.querySelectorAll('main section, .cartao')];alvos.forEach(a=>a.classList.add('revelar'));const observador=new IntersectionObserver(itens=>itens.forEach(i=>{if(i.isIntersecting){i.target.classList.add('visivel');observador.unobserve(i.target);}}),{threshold:.1});alvos.forEach(a=>observador.observe(a));}
function dicas(){const dicas=['Dica: use a busca para descrever a tarefa, não só o nome da ferramenta.','Dica: no Estúdio, ajuste o recorte e só depois gere a prévia.','Dica: marque suas ferramentas favoritas para encontrá-las mais rápido.'];let indice=0;setInterval(()=>{notificar(dicas[indice++%dicas.length]);},45000);}
export function iniciarExperiencia(categorias,abrir){inicializarMenu(categorias);inicializarModais();renderizarAvisos();renderizarBanners();renderizarFaq();renderizarRecentes(id=>abrir(id));iniciarBanner();revelarAoRolar();dicas();}
