/** Catálogo — Texto, Documentos e PDF, Imagens, Marketing. */
export const ferramentas = [
  {
    id: 'F051', slug: 'contador-de-texto', nome: 'Contador de texto', cat: 'texto',
    ícone: 'texto', tarefas: ['analisar'], status: 'planejada',
    resumo: 'Conta caracteres, palavras, frases e parágrafos, e estima o tempo de leitura.',
    problema: 'Saber se um texto cabe no limite de caracteres ou quanto tempo leva para ler.',
    entra: 'Texto colado ou digitado.',
    processa: 'Conta caracteres (com e sem espaço), palavras, frases e parágrafos.',
    sai: 'Contagens e tempo estimado de leitura e de fala.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['contar palavras', 'caracteres', 'tempo de leitura'],
    intenções: ['quantas palavras tem esse texto', 'contar caracteres para o twitter'],
  },
  {
    id: 'F052', slug: 'limpador-de-texto', nome: 'Limpeza de texto', cat: 'texto',
    ícone: 'texto', tarefas: ['organizar'], status: 'planejada',
    resumo: 'Remove espaços duplicados, linhas vazias e quebras de linha soltas.',
    problema: 'Colar um texto de outro lugar e ele vir cheio de espaços e linhas quebradas.',
    entra: 'Texto colado.',
    processa: 'Aplica as limpezas escolhidas preservando os parágrafos reais.',
    sai: 'Texto limpo pronto para copiar.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    unifica: ['Remover espaços extras', 'Padronizar quebras de linha', 'Remover linhas vazias'],
    tags: ['limpar texto', 'espaços', 'quebra de linha'],
    intenções: ['tirar espaço duplo do texto', 'limpar texto colado do pdf'],
  },
  {
    id: 'F053', slug: 'comparador-de-textos', nome: 'Comparar dois textos', cat: 'texto',
    ícone: 'filtro', tarefas: ['comparar'], status: 'planejada',
    resumo: 'Mostra as diferenças entre duas versões de um texto, linha a linha.',
    problema: 'Achar o que mudou entre duas versões de um contrato ou parágrafo.',
    entra: 'Dois textos.',
    processa: 'Compara linha a linha e destaca o que foi incluído, removido e alterado.',
    sai: 'Texto com as diferenças destacadas.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['comparar texto', 'diff', 'diferença'],
    intenções: ['o que mudou entre essas duas versões'],
  },
  {
    id: 'F054', slug: 'transformador-de-caixa', nome: 'Maiúsculas e minúsculas', cat: 'texto',
    ícone: 'texto', tarefas: ['converter'], status: 'planejada',
    resumo: 'Converte o texto para maiúsculas, minúsculas, Cada Palavra ou frase normal.',
    problema: 'Corrigir um texto digitado em CAIXA ALTA por engano.',
    entra: 'Texto.',
    processa: 'Aplica a transformação de caixa escolhida, respeitando siglas quando marcado.',
    sai: 'Texto convertido.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    unifica: ['Texto em maiúsculas', 'Texto em minúsculas', 'Primeira letra maiúscula', 'Título'],
    tags: ['maiúscula', 'minúscula', 'caixa alta', 'título'],
    intenções: ['transformar texto em maiúsculas', 'tirar caixa alta'],
  },
  {
    id: 'F055', slug: 'removedor-de-acentos', nome: 'Remover acentos', cat: 'texto',
    ícone: 'texto', tarefas: ['converter'], status: 'planejada',
    resumo: 'Remove acentos e caracteres especiais do texto, mantendo a pontuação.',
    problema: 'Gerar um texto sem acento para um sistema que não aceita.',
    entra: 'Texto.',
    processa: 'Normaliza os caracteres Unicode e remove os sinais diacríticos.',
    sai: 'Texto sem acentos.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['remover acento', 'normalizar texto'],
    intenções: ['tirar acento do texto'],
  },
  {
    id: 'F056', slug: 'remover-linhas-duplicadas-de-texto', nome: 'Remover linhas duplicadas', cat: 'texto',
    ícone: 'lista', tarefas: ['organizar'], status: 'planejada',
    resumo: 'Remove linhas repetidas de uma lista de texto, mantendo a primeira ocorrência.',
    problema: 'Limpar uma lista colada que tem itens repetidos.',
    entra: 'Texto com uma linha por item.',
    processa: 'Compara as linhas (ignorando espaços e maiúsculas quando marcado) e remove as repetidas.',
    sai: 'Lista sem duplicadas e a contagem de linhas removidas.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['duplicadas', 'lista', 'linhas repetidas'],
    intenções: ['tirar linhas repetidas da lista'],
  },
  {
    id: 'F057', slug: 'ordenador-de-linhas', nome: 'Ordenar linhas', cat: 'texto',
    ícone: 'lista', tarefas: ['organizar'], status: 'planejada',
    resumo: 'Ordena as linhas de um texto em ordem alfabética, numérica, reversa ou aleatória.',
    problema: 'Colocar uma lista em ordem sem copiar para uma planilha.',
    entra: 'Texto com uma linha por item.',
    processa: 'Ordena pelo critério escolhido, com opção de ignorar maiúsculas.',
    sai: 'Lista ordenada.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['ordenar', 'lista alfabética'],
    intenções: ['colocar lista em ordem alfabética'],
  },
  {
    id: 'F058', slug: 'modelo-de-mensagem', nome: 'Modelo de mensagem', cat: 'texto',
    ícone: 'balão', tarefas: ['criar'], status: 'planejada',
    resumo: 'Preenche modelos de aviso, cobrança e agradecimento com os dados informados.',
    problema: 'Escrever uma mensagem comum do dia a dia sem começar do zero.',
    entra: 'Tipo de mensagem e os dados a preencher.',
    processa: 'Insere os dados no modelo escolhido e ajusta a concordância.',
    sai: 'Mensagem pronta para copiar.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['modelo de mensagem', 'aviso', 'cobrança'],
    intenções: ['escrever mensagem de cobrança educada', 'modelo de aviso'],
  },
  {
    id: 'F059', slug: 'extrator-de-contatos-em-texto', nome: 'Extrair e-mails e telefones de um texto', cat: 'texto',
    ícone: 'busca', tarefas: ['analisar'], status: 'planejada',
    resumo: 'Localiza e lista e-mails, telefones e links soltos dentro de um texto.',
    problema: 'Puxar contatos de um texto colado sem procurar um por um.',
    entra: 'Texto.',
    processa: 'Aplica padrões de reconhecimento para cada tipo de dado.',
    sai: 'Listas separadas de e-mails, telefones e links encontrados.',
    exporta: ['copiar', 'csv'], plano: 'gratuito', local: true,
    tags: ['extrair email', 'extrair telefone', 'links'],
    intenções: ['tirar os emails desse texto', 'achar telefones no texto'],
  },
  {
    id: 'F060', slug: 'juntar-pdf', nome: 'Juntar PDF', cat: 'documentos',
    ícone: 'documento', tarefas: ['organizar'], status: 'planejada',
    resumo: 'Junta vários arquivos PDF em um único documento, na ordem escolhida.',
    problema: 'Mandar um só PDF em vez de vários arquivos soltos.',
    entra: 'Dois ou mais arquivos PDF.',
    processa: 'Combina as páginas de cada arquivo na ordem definida.',
    sai: 'Um PDF único para baixar.',
    exporta: ['baixar'], plano: 'gratuito', local: true,
    tags: ['juntar pdf', 'unir pdf', 'mesclar'],
    intenções: ['juntar vários pdf em um só'],
  },
  {
    id: 'F061', slug: 'dividir-pdf', nome: 'Dividir PDF e extrair páginas', cat: 'documentos',
    ícone: 'documento', tarefas: ['organizar'], status: 'planejada',
    resumo: 'Divide um PDF em partes ou extrai só as páginas escolhidas.',
    problema: 'Tirar algumas páginas de um PDF grande sem mexer no resto.',
    entra: 'Arquivo PDF e o intervalo de páginas.',
    processa: 'Separa as páginas pedidas em um novo arquivo.',
    sai: 'PDF com as páginas extraídas ou vários arquivos divididos.',
    exporta: ['baixar'], plano: 'gratuito', local: true,
    unifica: ['Dividir PDF', 'Extrair páginas do PDF'],
    tags: ['dividir pdf', 'extrair páginas', 'separar pdf'],
    intenções: ['tirar só uma página do pdf', 'dividir pdf em partes'],
  },
  {
    id: 'F062', slug: 'girar-e-numerar-pdf', nome: 'Girar e numerar páginas do PDF', cat: 'documentos',
    ícone: 'documento', tarefas: ['organizar'], status: 'planejada',
    resumo: "Gira páginas na orientação certa e adiciona numeração no rodapé.",
    problema: 'Corrigir páginas escaneadas de lado e numerar um documento longo.',
    entra: 'Arquivo PDF, páginas a girar e formato da numeração.',
    processa: 'Rotaciona as páginas escolhidas e desenha o número em cada página.',
    sai: 'PDF corrigido e numerado.',
    exporta: ['baixar'], plano: 'gratuito', local: true,
    unifica: ['Girar páginas do PDF', 'Numerar páginas do PDF'],
    tags: ['girar pdf', 'numerar página', 'paginação'],
    intenções: ['página do pdf está de lado', 'numerar páginas do pdf'],
  },
  {
    id: 'F063', slug: 'protecao-de-pdf', nome: "Marca d'água e senha no PDF", cat: 'documentos',
    ícone: 'cadeado', tarefas: ['criar'], status: 'planejada',
    resumo: "Adiciona marca d'água de texto ou protege o PDF com senha de abertura.",
    problema: 'Identificar um PDF como rascunho ou impedir que qualquer um abra o arquivo.',
    entra: "Arquivo PDF, texto da marca d'água ou senha desejada.",
    processa: "Desenha a marca d'água em cada página ou aplica a criptografia do arquivo.",
    sai: "PDF com marca d'água ou protegido por senha.",
    exporta: ['baixar'], plano: 'plus', local: false,
    unifica: ["Marca d'água em PDF", 'Proteger PDF com senha'],
    tags: ["marca d'água", 'proteger pdf', 'senha no pdf'],
    intenções: ["colocar marca d'água no pdf", 'proteger pdf com senha'],
  },
  {
    id: 'F064', slug: 'comprimir-pdf', nome: 'Comprimir PDF', cat: 'documentos',
    ícone: 'documento', tarefas: ['organizar'], status: 'planejada',
    resumo: 'Reduz o tamanho do arquivo PDF recomprimindo as imagens internas.',
    problema: 'Enviar um PDF grande por e-mail ou formulário com limite de tamanho.',
    entra: 'Arquivo PDF.',
    processa: 'Recomprime as imagens internas mantendo o texto intacto.',
    sai: 'PDF menor, com o tamanho antes e depois.',
    exporta: ['baixar'], plano: 'plus', local: true,
    tags: ['comprimir pdf', 'reduzir tamanho'],
    intenções: ['diminuir tamanho do pdf'],
  },
  {
    id: 'F065', slug: 'extrair-texto-de-pdf', nome: 'Extrair texto do PDF', cat: 'documentos',
    ícone: 'documento', tarefas: ['analisar'], status: 'planejada',
    resumo: 'Puxa o texto de um PDF para copiar ou editar, página por página.',
    problema: 'Copiar o conteúdo de um PDF sem digitar tudo de novo.',
    entra: 'Arquivo PDF.',
    processa: 'Lê o texto embutido de cada página no próprio navegador.',
    sai: 'Texto extraído, com aviso quando o PDF é uma imagem escaneada sem texto.',
    exporta: ['copiar', 'baixar'], plano: 'gratuito', local: true,
    tags: ['extrair texto do pdf', 'pdf para texto'],
    intenções: ['copiar texto de um pdf'],
  },
  {
    id: 'F066', slug: 'declaracao', nome: 'Gerador de declaração', cat: 'documentos',
    ícone: 'documento', tarefas: ['criar'], status: 'planejada',
    resumo: 'Monta declarações simples (residência, próprio punho, para os fins que couber) em PDF.',
    problema: 'Escrever uma declaração formal sem lembrar a estrutura certa.',
    entra: 'Tipo de declaração, dados das partes e finalidade.',
    processa: 'Preenche o modelo com os dados e monta o documento em A4.',
    sai: 'Declaração em PDF com linha de assinatura.',
    exporta: ['pdf', 'imprimir'], plano: 'gratuito', local: true,
    tags: ['declaração', 'documento simples'],
    intenções: ['fazer uma declaração de residência'],
  },
  {
    id: 'F067', slug: 'procuracao', nome: 'Gerador de procuração', cat: 'documentos',
    ícone: 'documento', tarefas: ['criar'], status: 'planejada',
    resumo: 'Monta uma procuração simples com outorgante, outorgado e poderes concedidos.',
    problema: 'Redigir uma procuração sem contratar um advogado para um ato simples.',
    entra: 'Dados de quem outorga, de quem recebe e os poderes concedidos.',
    processa: 'Preenche o modelo padrão e monta o documento em A4.',
    sai: 'Procuração em PDF com linha de assinatura e aviso de que não substitui orientação jurídica.',
    exporta: ['pdf', 'imprimir'], plano: 'gratuito', local: true,
    tags: ['procuração', 'poderes'],
    intenções: ['fazer uma procuração simples'],
  },
  {
    id: 'F068', slug: 'contrato-simples', nome: 'Contrato simples de prestação de serviço', cat: 'documentos',
    ícone: 'documento', tarefas: ['criar'], status: 'planejada',
    resumo: 'Monta um contrato curto de prestação de serviço com objeto, valor e prazo.',
    problema: 'Formalizar um acordo simples sem abrir um editor de texto do zero.',
    entra: 'Partes, objeto do serviço, valor, forma de pagamento e prazo.',
    processa: 'Preenche o modelo com cláusulas básicas e monta o documento em A4.',
    sai: 'Contrato em PDF com linha de assinatura das partes.',
    exporta: ['pdf', 'imprimir'], plano: 'gratuito', local: true,
    tags: ['contrato', 'prestação de serviço'],
    intenções: ['fazer um contrato simples de serviço'],
  },
  {
    id: 'F069', slug: 'checklist', nome: 'Checklist para imprimir', cat: 'documentos',
    ícone: 'lista', tarefas: ['criar', 'organizar'], status: 'planejada',
    resumo: 'Monta uma lista de tarefas com caixas de marcar, para qualquer finalidade.',
    problema: 'Organizar os itens de uma viagem, mudança, evento ou projeto numa lista só.',
    entra: 'Título e os itens da lista.',
    processa: 'Numera os itens e monta a lista com caixa de marcar ao lado de cada um.',
    sai: 'Checklist na tela, para copiar, imprimir ou salvar em PDF.',
    exporta: ['pdf', 'imprimir', 'copiar'], plano: 'gratuito', local: true,
    origem: 'porte',
    tags: ['checklist', 'lista de tarefas'],
    intenções: ['fazer um checklist para imprimir'],
  },
  {
    id: 'F070', slug: 'pop', nome: 'Procedimento operacional padrão (POP)', cat: 'documentos',
    ícone: 'documento', tarefas: ['criar'], status: 'planejada',
    resumo: 'Monta um POP com objetivo, materiais, passo a passo e responsável.',
    problema: 'Documentar um processo da empresa de um jeito padronizado.',
    entra: 'Nome do processo, objetivo, materiais, etapas e responsáveis.',
    processa: 'Organiza as etapas numeradas e monta o documento com cabeçalho padrão.',
    sai: 'POP em PDF pronto para treinar a equipe.',
    exporta: ['pdf', 'imprimir'], plano: 'gratuito', local: true,
    tags: ['pop', 'procedimento', 'processo'],
    intenções: ['documentar um processo da empresa'],
  },
  {
    id: 'F071', slug: 'curriculo', nome: 'Gerador de currículo', cat: 'documentos',
    ícone: 'pessoas', tarefas: ['criar'], status: 'planejada',
    resumo: 'Monta um currículo organizado com experiência, formação e habilidades.',
    problema: 'Ter um currículo com boa formatação sem brigar com o editor de texto.',
    entra: 'Dados pessoais, experiências, formação e habilidades.',
    processa: 'Organiza as seções em ordem cronológica e monta o layout em A4.',
    sai: 'Currículo em PDF pronto para enviar.',
    exporta: ['pdf', 'imprimir'], plano: 'gratuito', local: true,
    tags: ['currículo', 'emprego', 'vaga'],
    intenções: ['fazer um currículo'],
  },
  {
    id: 'F072', slug: 'etiquetas', nome: 'Etiquetas para imprimir', cat: 'documentos',
    ícone: 'grade', tarefas: ['criar', 'exportar'], status: 'planejada',
    resumo: 'Calcula quantas etiquetas de um tamanho cabem numa folha A4 e gera o PDF de corte.',
    problema: 'Imprimir etiquetas de endereço ou de produto numa folha sem desperdiçar espaço.',
    entra: 'Tamanho da etiqueta, margens e o texto de cada uma.',
    processa: 'Monta a grade de etiquetas que cabe na folha e distribui o texto de cada uma.',
    sai: 'PDF com as etiquetas posicionadas e linhas de corte.',
    exporta: ['pdf', 'imprimir'], plano: 'gratuito', local: true,
    origem: 'porte',
    tags: ['etiquetas', 'rótulos', 'imprimir'],
    intenções: ['imprimir etiquetas em folha a4'],
  },
  {
    id: 'F073', slug: 'redimensionar-imagens-em-lote', nome: 'Redimensionar imagens em lote', cat: 'imagens',
    ícone: 'imagem', tarefas: ['converter'], status: 'planejada',
    resumo: 'Redimensiona várias imagens de uma vez para o tamanho ou peso desejado.',
    problema: 'Ajustar o tamanho de muitas fotos sem abrir uma por uma num editor.',
    entra: 'Várias imagens e a medida ou peso final desejado.',
    processa: 'Redimensiona cada imagem mantendo a proporção, no próprio navegador.',
    sai: 'Imagens redimensionadas para baixar, uma por uma ou em pacote.',
    exporta: ['baixar'], plano: 'plus', local: true,
    tags: ['redimensionar imagem', 'lote', 'tamanho'],
    intenções: ['redimensionar várias fotos de uma vez'],
  },
  {
    id: 'F074', slug: 'cortar-imagem', nome: 'Cortar imagem', cat: 'imagens',
    ícone: 'imagem', tarefas: ['criar'], status: 'planejada',
    resumo: 'Corta a imagem livremente ou numa proporção pronta para post, story ou capa.',
    problema: 'Ajustar uma foto para o formato exigido por uma rede social.',
    entra: 'Imagem e a proporção ou moldura desejada.',
    processa: 'Recorta a área escolhida mantendo a resolução original.',
    sai: 'Imagem cortada, pronta para baixar.',
    exporta: ['baixar', 'png'], plano: 'gratuito', local: true,
    unifica: ['Cortar imagem', 'Imagem para redes sociais'],
    tags: ['cortar imagem', 'recorte', 'redes sociais', 'story'],
    intenções: ['cortar imagem para o instagram', 'recortar foto'],
  },
  {
    id: 'F075', slug: 'converter-formato-de-imagem', nome: 'Converter formato de imagem', cat: 'imagens',
    ícone: 'imagem', tarefas: ['converter'], status: 'planejada',
    resumo: 'Converte entre JPG, PNG, WebP e outros formatos de imagem.',
    problema: 'Ter a imagem no formato exigido por um site ou sistema.',
    entra: 'Imagem e o formato de saída.',
    processa: 'Reconverte a imagem no próprio navegador, com controle de qualidade.',
    sai: 'Arquivo no novo formato para baixar.',
    exporta: ['baixar', 'png'], plano: 'gratuito', local: true,
    tags: ['converter imagem', 'jpg', 'png', 'webp'],
    intenções: ['converter png para jpg', 'transformar imagem em webp'],
  },
  {
    id: 'F076', slug: 'comprimir-imagem', nome: 'Comprimir imagem', cat: 'imagens',
    ícone: 'imagem', tarefas: ['converter'], status: 'planejada',
    resumo: 'Reduz o peso da imagem controlando a qualidade, sem trocar o formato.',
    problema: 'Deixar a foto leve o suficiente para o site carregar rápido.',
    entra: 'Imagem e o nível de qualidade ou peso máximo desejado.',
    processa: 'Recomprime a imagem no navegador testando a qualidade até atingir o alvo.',
    sai: 'Imagem comprimida, com o tamanho antes e depois.',
    exporta: ['baixar'], plano: 'gratuito', local: true,
    tags: ['comprimir imagem', 'otimizar imagem', 'peso'],
    intenções: ['deixar a imagem mais leve'],
  },
  {
    id: 'F077', slug: 'gerador-de-favicon', nome: 'Gerador de favicon', cat: 'imagens',
    ícone: 'imagem', tarefas: ['criar'], status: 'planejada',
    resumo: 'Gera o favicon do site em vários tamanhos a partir de uma imagem.',
    problema: 'Ter o ícone do site nos tamanhos certos sem abrir editor de imagem.',
    entra: 'Uma imagem quadrada.',
    processa: 'Redimensiona para os tamanhos padrão de favicon e monta o pacote.',
    sai: 'Arquivos de favicon em vários tamanhos, prontos para baixar.',
    exporta: ['baixar'], plano: 'gratuito', local: true,
    tags: ['favicon', 'ícone do site'],
    intenções: ['gerar favicon do site'],
  },
  {
    id: 'F078', slug: 'remover-metadados-de-imagem', nome: 'Remover metadados da imagem', cat: 'imagens',
    ícone: 'cadeado', tarefas: ['organizar'], status: 'planejada',
    resumo: 'Apaga dados de localização, câmera e data escondidos dentro do arquivo da foto.',
    problema: 'Publicar uma foto sem revelar onde e com qual aparelho ela foi tirada.',
    entra: 'Imagem.',
    processa: 'Lê os metadados EXIF e gera uma cópia sem essas informações.',
    sai: 'Imagem limpa e a lista do que foi removido.',
    exporta: ['baixar'], plano: 'gratuito', local: true,
    tags: ['metadados', 'exif', 'privacidade da foto'],
    intenções: ['tirar localização da foto', 'remover exif'],
  },
  {
    id: 'F079', slug: 'extrator-de-paleta-de-cores', nome: 'Extrair paleta de cores da imagem', cat: 'imagens',
    ícone: 'imagem', tarefas: ['analisar'], status: 'planejada',
    resumo: 'Identifica as cores predominantes de uma imagem e devolve os códigos hexadecimais.',
    problema: 'Descobrir as cores exatas de uma imagem para usar no design.',
    entra: 'Imagem.',
    processa: 'Agrupa os pixels por cor semelhante e ordena pela predominância.',
    sai: 'Paleta de cores com os códigos hexadecimais e RGB.',
    exporta: ['copiar', 'png'], plano: 'gratuito', local: true,
    tags: ['paleta de cores', 'extrair cor', 'hexadecimal'],
    intenções: ['pegar as cores dessa imagem'],
  },
  {
    id: 'F080', slug: 'verificador-de-contraste', nome: 'Verificador de contraste de cores', cat: 'imagens',
    ícone: 'confere-círculo', tarefas: ['validar'], status: 'planejada',
    resumo: 'Confere se a combinação de cor do texto e do fundo atende às regras de acessibilidade.',
    problema: 'Saber se um texto vai ficar legível em cima de determinada cor de fundo.',
    entra: 'Cor do texto e cor do fundo.',
    processa: 'Calcula a razão de contraste e compara com os critérios WCAG.',
    sai: 'Razão de contraste e se passa nos níveis AA e AAA.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['contraste', 'acessibilidade', 'wcag'],
    intenções: ['esse texto tem contraste suficiente'],
  },
  {
    id: 'F081', slug: 'calendario-editorial', nome: 'Calendário editorial', cat: 'marketing',
    ícone: 'datas', tarefas: ['organizar'], status: 'planejada',
    resumo: 'Organiza os posts do mês por data, rede social e status de produção.',
    problema: 'Planejar o conteúdo do mês sem perder o fio em uma planilha solta.',
    entra: 'Datas, temas, rede social e status de cada post.',
    processa: 'Organiza os posts em uma grade mensal por data e status.',
    sai: 'Calendário do mês, para exportar ou imprimir.',
    exporta: ['xlsx', 'pdf'], plano: 'gratuito', local: true,
    tags: ['calendário editorial', 'conteúdo', 'rede social'],
    intenções: ['planejar postagens do mês'],
  },
  {
    id: 'F082', slug: 'gerador-de-titulos', nome: 'Gerador de títulos', cat: 'marketing',
    ícone: 'texto', tarefas: ['criar'], status: 'planejada',
    resumo: 'Sugere variações de título para post, anúncio ou e-mail a partir do assunto.',
    problema: 'Testar várias formas de chamar a atenção sem travar na primeira ideia.',
    entra: 'Assunto, público e objetivo do título.',
    processa: 'Monta variações a partir de estruturas comuns de título.',
    sai: 'Lista de títulos sugeridos para escolher e ajustar.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['título', 'headline', 'copywriting'],
    intenções: ['sugestão de título para o post'],
  },
  {
    id: 'F083', slug: 'gerador-de-descricao-de-produto', nome: 'Gerador de descrição de produto', cat: 'marketing',
    ícone: 'texto', tarefas: ['criar'], status: 'planejada',
    resumo: 'Monta a descrição de um produto a partir de características e benefícios informados.',
    problema: 'Escrever a descrição do produto para o anúncio ou a loja sem enrolar.',
    entra: 'Nome do produto, características, benefícios e tom desejado.',
    processa: 'Organiza as informações num texto corrido com estrutura de característica e benefício.',
    sai: 'Descrição pronta para copiar.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['descrição de produto', 'anúncio', 'loja'],
    intenções: ['escrever descrição de produto para anúncio'],
  },
  {
    id: 'F084', slug: 'briefing-criativo', nome: 'Briefing criativo', cat: 'marketing',
    ícone: 'documento', tarefas: ['criar'], status: 'planejada',
    resumo: 'Organiza objetivo, público, tom e referências antes de pedir uma peça de conteúdo.',
    problema: 'Passar um pedido de criação sem esquecer informação importante.',
    entra: 'Objetivo, público-alvo, tom de voz, prazo e referências.',
    processa: 'Organiza as respostas num documento estruturado.',
    sai: 'Briefing em PDF pronto para enviar ao criador ou à equipe.',
    exporta: ['pdf', 'copiar'], plano: 'gratuito', local: true,
    tags: ['briefing', 'conteúdo', 'criação'],
    intenções: ['fazer um briefing para o designer'],
  },
];
