/** Catálogo — Cálculo, Datas, Planilhas, Desenvolvimento e Segurança. */
export const ferramentas = [
  {
    id: 'F021', slug: 'regra-de-tres', nome: 'Regra de três', cat: 'cálculo',
    ícone: 'cálculo', tarefas: ['calcular'], status: 'pronta',
    resumo: 'Proporção direta e inversa, com a conta montada passo a passo.',
    problema: 'Resolver proporções sem trocar a ordem dos termos.',
    entra: 'Três valores conhecidos e o tipo de proporção.',
    processa: 'Monta a proporção direta ou inversa e isola a incógnita.',
    sai: 'Valor procurado e a conta montada.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    unifica: ['Regra de três simples', 'Regra de três inversa'],
    tags: ['regra de três', 'proporção', 'proporcional'],
    intenções: ['regra de três', 'se 3 custam x quanto custam 7'],
  },
  {
    id: 'F022', slug: 'conversor-de-unidades', nome: 'Conversor de unidades', cat: 'cálculo',
    ícone: 'régua', tarefas: ['converter'], status: 'pronta',
    resumo: 'Massa, comprimento, área, volume, temperatura, velocidade, tempo e dados digitais.',
    problema: 'Converter medidas entre sistemas sem procurar tabela.',
    entra: 'Valor, grandeza e as duas unidades.',
    processa: 'Converte pela unidade base da grandeza; temperatura usa fórmula própria.',
    sai: 'Valor convertido e equivalências úteis da mesma grandeza.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    unifica: ['Conversor de medidas', 'Conversor de temperatura', 'Conversor de bytes'],
    tags: ['converter', 'metro', 'quilo', 'litro', 'celsius', 'polegada', 'byte'],
    intenções: ['converter unidades', 'quantos gramas tem uma xícara', 'celsius para fahrenheit'],
  },
  {
    id: 'F023', slug: 'calculadora-de-datas', nome: 'Calculadora de datas', cat: 'datas',
    ícone: 'datas', tarefas: ['calcular'], status: 'pronta',
    resumo: 'Diferença entre datas, somar ou subtrair prazos, dias úteis, idade e dia da semana.',
    problema: 'Descobrir prazos e idades sem contar no calendário.',
    entra: 'Uma ou duas datas, quantidade de dias e feriados opcionais.',
    processa: 'Opera em datas locais sem fuso, pulando fins de semana e feriados quando pedido.',
    sai: 'Diferença detalhada, data final, dia da semana e idade em várias unidades.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    unifica: ['Diferença entre datas', 'Dias úteis', 'Calculadora de idade', 'Dia da semana', 'Dia do ano'],
    tags: ['data', 'prazo', 'dias úteis', 'idade', 'vencimento'],
    intenções: ['quantos dias faltam', 'calcular prazo em dias úteis', 'qual minha idade exata'],
  },
  {
    id: 'F024', slug: 'calculadora-de-horas', nome: 'Calculadora de horas', cat: 'datas',
    ícone: 'relógio', tarefas: ['calcular'], status: 'pronta',
    resumo: 'Soma jornadas com intervalo, calcula carga horária, extras e saldo de banco de horas.',
    problema: 'Fechar a folha de ponto sem errar a conta de minutos.',
    entra: 'Entradas e saídas do dia, intervalo e jornada contratual.',
    processa: 'Converte tudo para minutos, desconta intervalo e compara com a jornada.',
    sai: 'Horas trabalhadas, saldo positivo ou negativo e total do período.',
    exporta: ['copiar', 'xlsx'], plano: 'gratuito', local: true,
    unifica: ['Somar horas', 'Carga horária', 'Banco de horas'],
    tags: ['horas', 'ponto', 'jornada', 'hora extra', 'banco de horas'],
    intenções: ['somar horas trabalhadas', 'calcular hora extra', 'fechar o ponto'],
  },
  {
    id: 'F025', slug: 'json', nome: 'JSON: validar e formatar', cat: 'desenvolvimento',
    ícone: 'código', tarefas: ['validar', 'converter'], status: 'pronta',
    resumo: 'Valida, indenta, minifica, ordena chaves e aponta o erro com linha e coluna.',
    problema: 'Achar rapidamente onde o JSON quebrou e deixá-lo legível.',
    entra: 'Texto JSON colado ou arquivo.',
    processa: 'Analisa com o interpretador do navegador e localiza o ponto do erro.',
    sai: 'JSON formatado ou minificado, com estatísticas de chaves e profundidade.',
    exporta: ['copiar', 'baixar'], plano: 'gratuito', local: true,
    unifica: ['Formatador de JSON', 'Validador de JSON', 'Minificador de JSON'],
    tags: ['json', 'formatar', 'validar', 'api'],
    intenções: ['meu json está inválido', 'formatar json'],
  },
  {
    id: 'F026', slug: 'base64', nome: 'Base64: codificar e decodificar', cat: 'desenvolvimento',
    ícone: 'código', tarefas: ['converter'], status: 'pronta',
    resumo: 'Texto e arquivo para Base64 e de volta, com suporte a UTF-8 e URL-safe.',
    problema: 'Converter dados para Base64 sem quebrar acentos.',
    entra: 'Texto ou arquivo.',
    processa: 'Codifica em UTF-8 antes de converter; decodifica validando o conteúdo.',
    sai: 'Texto convertido pronto para copiar ou baixar.',
    exporta: ['copiar', 'baixar'], plano: 'gratuito', local: true,
    tags: ['base64', 'codificar', 'decodificar'], intenções: ['converter para base64'],
  },
  {
    id: 'F027', slug: 'gerador-de-senhas', nome: 'Gerador de senhas', cat: 'segurança',
    ícone: 'chave', tarefas: ['criar'], status: 'pronta',
    resumo: 'Senhas fortes, PIN, senha de Wi-Fi e frase-senha, com medidor de força real.',
    problema: 'Criar segredos fortes sem inventar padrões previsíveis.',
    entra: 'Tamanho, conjuntos de caracteres e quantidade.',
    processa: 'Usa `crypto.getRandomValues` com amostragem sem viés e estima a entropia em bits.',
    sai: 'Senhas geradas, entropia em bits e tempo estimado de quebra.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    unifica: ['Gerador de PIN', 'Senha de Wi-Fi', 'Verificador de força de senha'],
    tags: ['senha', 'pin', 'wifi', 'segurança', 'aleatório'],
    intenções: ['criar senha forte', 'gerar pin', 'senha do wifi'],
  },
  {
    id: 'F028', slug: 'validador-cpf-cnpj', nome: 'Validador de CPF e CNPJ', cat: 'segurança',
    ícone: 'confere-círculo', tarefas: ['validar'], status: 'pronta',
    resumo: 'Confere os dígitos verificadores de CPF e CNPJ e formata o número.',
    problema: 'Saber se um documento foi digitado errado antes de usar no cadastro.',
    entra: 'CPF ou CNPJ, com ou sem pontuação.',
    processa: 'Recalcula os dígitos verificadores pelo módulo 11 e rejeita sequências repetidas.',
    sai: 'Válido ou inválido, com o número formatado e o motivo da recusa.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    unifica: ['Validador de CPF', 'Validador de CNPJ'],
    tags: ['cpf', 'cnpj', 'validar', 'documento'],
    intenções: ['esse cpf é válido', 'conferir cnpj'],
  },
  {
    id: 'F029', slug: 'qr-code', nome: 'Gerador de QR Code', cat: 'imagens',
    ícone: 'grade', tarefas: ['criar', 'exportar'], status: 'pronta',
    resumo: 'QR Code de link, texto, Wi-Fi ou contato, com download em PNG e SVG.',
    problema: 'Gerar um QR Code sem enviar o conteúdo para um site desconhecido.',
    entra: 'Tipo de conteúdo e os dados correspondentes.',
    processa: 'Monta o texto no formato do padrão e gera a matriz no próprio navegador.',
    sai: 'QR Code em tela, PNG e SVG.',
    exporta: ['baixar'], plano: 'gratuito', local: true,
    unifica: ['QR Code de Wi-Fi', 'QR Code de contato', 'QR Code de link'],
    tags: ['qr code', 'wifi', 'link', 'contato'], intenções: ['gerar qr code'],
  },
  {
    id: 'F030', slug: 'limpar-planilha', nome: 'Limpeza de planilha', cat: 'planilhas',
    ícone: 'planilha', tarefas: ['organizar'], status: 'pronta',
    resumo: 'Remove linhas duplicadas e vazias, apara espaços, padroniza maiúsculas e exporta CSV ou XLSX.',
    problema: 'Deixar uma lista exportada de outro sistema utilizável.',
    entra: 'Arquivo CSV ou texto colado, com o separador detectado automaticamente.',
    processa: 'Interpreta o CSV respeitando aspas, aplica as limpezas escolhidas e recalcula os totais.',
    sai: 'Tabela limpa, contagem do que foi removido e arquivo para baixar.',
    exporta: ['csv', 'xlsx', 'copiar'], plano: 'gratuito', local: true,
    unifica: ['Remover linhas duplicadas', 'Aparar espaços', 'Padronizar texto de planilha'],
    tags: ['csv', 'planilha', 'duplicadas', 'limpar', 'excel'],
    intenções: ['tirar duplicados da planilha', 'limpar csv'],
  },
  {
    id: 'F031', slug: 'csv-e-json', nome: 'CSV e JSON', cat: 'planilhas',
    ícone: 'planilha', tarefas: ['converter'], status: 'pronta',
    resumo: 'Converte CSV em JSON e JSON em CSV, com separador e cabeçalho configuráveis.',
    problema: 'Levar dados de uma planilha para uma API e vice-versa.',
    entra: 'Texto CSV ou JSON, ou arquivo.',
    processa: 'Interpreta respeitando aspas e quebras de linha dentro de células.',
    sai: 'Arquivo convertido, em UTF-8, pronto para baixar.',
    exporta: ['copiar', 'baixar'], plano: 'gratuito', local: true,
    tags: ['csv', 'json', 'converter', 'dados'], intenções: ['converter csv para json'],
  },
  {
    id: 'F032', slug: 'comparar-planilhas', nome: 'Comparar duas planilhas', cat: 'planilhas',
    ícone: 'filtro', tarefas: ['comparar'], status: 'planejada',
    resumo: 'Mostra o que entrou, o que saiu e o que mudou entre duas versões da mesma lista.',
    problema: 'Descobrir a diferença entre dois arquivos sem conferir linha a linha.',
    entra: 'Duas planilhas e a coluna-chave.', processa: 'Casa as linhas pela chave e compara campo a campo.',
    sai: 'Listas de incluídos, removidos e alterados.',
    exporta: ['xlsx', 'csv'], plano: 'gratuito', local: true,
    tags: ['comparar', 'diferença', 'planilha'], intenções: ['o que mudou entre as duas planilhas'],
  },
  {
    id: 'F033', slug: 'estatistica-descritiva', nome: 'Estatística de uma coluna', cat: 'planilhas',
    ícone: 'gráfico', tarefas: ['analisar'], status: 'planejada',
    resumo: 'Média, mediana, moda, desvio padrão, quartis e detecção de valores fora da curva.',
    problema: 'Entender um conjunto de números sem abrir o Excel.',
    entra: 'Lista de números colada ou coluna de um CSV.',
    processa: 'Calcula as medidas e marca valores atípicos pelo critério do intervalo interquartil.',
    sai: 'Resumo estatístico e distribuição.',
    exporta: ['copiar', 'xlsx'], plano: 'gratuito', local: true,
    tags: ['média', 'mediana', 'desvio padrão', 'estatística'], intenções: ['calcular média e desvio'],
  },
  {
    id: 'F034', slug: 'gerador-de-formulas', nome: 'Montador de fórmulas de planilha', cat: 'planilhas',
    ícone: 'código', tarefas: ['criar'], status: 'planejada',
    resumo: 'Monta PROCV, PROCX, SOMASES, CONT.SES e SE aninhado a partir de perguntas simples.',
    problema: 'Escrever a fórmula certa sem decorar a ordem dos argumentos.',
    entra: 'Intervalos, critérios e o que se quer obter.',
    processa: 'Monta a fórmula na sintaxe do Excel e do Google Planilhas.',
    sai: 'Fórmula pronta nas duas sintaxes, com explicação de cada argumento.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['procv', 'procx', 'somases', 'fórmula', 'excel'], intenções: ['como fazer procv'],
  },
  {
    id: 'F035', slug: 'dados-de-teste', nome: 'Gerador de dados de teste', cat: 'planilhas',
    ícone: 'planilha', tarefas: ['criar'], status: 'planejada',
    resumo: 'Gera listas fictícias de pessoas, produtos e pedidos para testar planilhas e sistemas.',
    problema: 'Testar um sistema sem usar dados reais de pessoas.',
    entra: 'Colunas desejadas e quantidade de linhas.',
    processa: 'Gera valores sintéticos, incluindo CPF e CNPJ matematicamente válidos mas fictícios.',
    sai: 'Tabela pronta em CSV, XLSX ou JSON.',
    exporta: ['csv', 'xlsx', 'json'], plano: 'gratuito', local: true,
    tags: ['dados falsos', 'teste', 'mock'], intenções: ['gerar dados para teste'],
  },
  {
    id: 'F036', slug: 'hash', nome: 'Gerador de hash', cat: 'segurança',
    ícone: 'cadeado', tarefas: ['criar', 'validar'], status: 'planejada',
    resumo: 'SHA-1, SHA-256, SHA-384 e SHA-512 de texto ou arquivo, para conferir integridade.',
    problema: 'Conferir se um arquivo baixado é igual ao original.',
    entra: 'Texto ou arquivo.', processa: 'Usa a Web Crypto API do navegador.',
    sai: 'Hash em hexadecimal, com comparação contra um valor esperado.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['hash', 'sha256', 'integridade'], intenções: ['conferir hash do arquivo'],
  },
  {
    id: 'F037', slug: 'uuid', nome: 'Gerador de identificadores', cat: 'desenvolvimento',
    ícone: 'código', tarefas: ['criar'], status: 'planejada',
    resumo: 'UUID v4, identificadores curtos e códigos legíveis, em lote.',
    problema: 'Criar identificadores únicos sem repetição.',
    entra: 'Formato e quantidade.', processa: 'Usa fonte criptográfica de aleatoriedade.',
    sai: 'Lista de identificadores.', exporta: ['copiar', 'baixar'], plano: 'gratuito', local: true,
    tags: ['uuid', 'id', 'código'], intenções: ['gerar uuid'],
  },
  {
    id: 'F038', slug: 'regex', nome: 'Testador de expressão regular', cat: 'desenvolvimento',
    ícone: 'busca', tarefas: ['validar'], status: 'planejada',
    resumo: 'Testa padrões com destaque das correspondências, grupos e substituição.',
    problema: 'Ajustar uma expressão regular vendo o efeito em tempo real.',
    entra: 'Expressão, sinalizadores e texto de teste.',
    processa: 'Executa com limite de tempo para evitar travamento por retrocesso.',
    sai: 'Correspondências destacadas, grupos capturados e resultado da substituição.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['regex', 'expressão regular'], intenções: ['testar regex'],
  },
  {
    id: 'F039', slug: 'timestamp', nome: 'Conversor de timestamp', cat: 'desenvolvimento',
    ícone: 'relógio', tarefas: ['converter'], status: 'planejada',
    resumo: 'Unix, milissegundos e ISO 8601 em data legível, com fuso escolhido.',
    problema: 'Ler uma data que veio como número num log ou API.',
    entra: 'Timestamp ou data.', processa: 'Converte entre os formatos preservando o fuso informado.',
    sai: 'Data legível, ISO e timestamp.', exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['timestamp', 'unix', 'iso'], intenções: ['converter timestamp'],
  },
  {
    id: 'F040', slug: 'url-e-codificacao', nome: 'Codificador de URL e HTML', cat: 'desenvolvimento',
    ícone: 'código', tarefas: ['converter'], status: 'planejada',
    resumo: 'Codifica e decodifica URL, parâmetros de consulta e entidades HTML.',
    problema: 'Montar ou ler URLs com acentos e caracteres especiais.',
    entra: 'Texto ou URL.', processa: 'Aplica a codificação percentual ou de entidades.',
    sai: 'Texto convertido e a lista de parâmetros da URL.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['url', 'encode', 'html'], intenções: ['codificar url'],
  },
  {
    id: 'F041', slug: 'gerador-de-link-whatsapp', nome: 'Link de WhatsApp', cat: 'marketing',
    ícone: 'balão', tarefas: ['criar'], status: 'planejada',
    resumo: 'Monta o link wa.me com número e mensagem pronta, mais o QR Code correspondente.',
    problema: 'Levar o cliente direto para a conversa já com a mensagem escrita.',
    entra: 'Número com DDI e DDD e a mensagem.',
    processa: 'Normaliza o número e codifica a mensagem.',
    sai: 'Link pronto e QR Code.', exporta: ['copiar', 'baixar'], plano: 'gratuito', local: true,
    tags: ['whatsapp', 'link', 'wa.me'], intenções: ['criar link do whatsapp'],
  },
  {
    id: 'F042', slug: 'utm', nome: 'Montador e leitor de UTM', cat: 'marketing',
    ícone: 'alvo', tarefas: ['criar', 'analisar'], status: 'planejada',
    resumo: 'Monta URLs com parâmetros de campanha e lê os parâmetros de uma URL existente.',
    problema: 'Marcar campanhas sem errar o padrão dos parâmetros.',
    entra: 'URL base e os campos de campanha.',
    processa: 'Codifica e normaliza os valores, avisando sobre maiúsculas e espaços.',
    sai: 'URL final e tabela de parâmetros.', exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['utm', 'campanha', 'analytics'], intenções: ['criar link com utm'],
  },
  {
    id: 'F043', slug: 'cronometro', nome: 'Cronômetro e temporizador', cat: 'produtividade',
    ícone: 'relógio', tarefas: ['organizar'], status: 'planejada',
    resumo: 'Cronômetro com voltas, temporizador regressivo e ciclos de foco.',
    problema: 'Marcar tempo sem depender do celular ao lado.',
    entra: 'Tempo ou ciclos.', processa: 'Conta o tempo com relógio de alta precisão do navegador.',
    sai: 'Tempo decorrido, voltas e aviso ao terminar.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    unifica: ['Pomodoro', 'Cronômetro', 'Temporizador'],
    tags: ['cronômetro', 'timer', 'pomodoro', 'foco'], intenções: ['marcar o tempo'],
  },
  {
    id: 'F044', slug: 'sorteio', nome: 'Sorteio', cat: 'produtividade',
    ícone: 'estrela', tarefas: ['criar'], status: 'pronta',
    resumo: 'Sorteia números, nomes e divide participantes em times, sem repetição quando pedido.',
    problema: 'Fazer um sorteio justo e verificável na frente de todo mundo.',
    entra: 'Faixa de números ou lista de nomes e a quantidade a sortear.',
    processa: 'Embaralha com fonte criptográfica e registra a semente do sorteio.',
    sai: 'Resultado sorteado, ordem completa e registro do sorteio.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    unifica: ['Sorteador de números', 'Sorteador de nomes', 'Sorteador de times', 'Amigo secreto'],
    tags: ['sorteio', 'sortear', 'times', 'amigo secreto', 'rifa'],
    intenções: ['fazer um sorteio', 'dividir times', 'sortear nomes'],
  },
  {
    id: 'F045', slug: 'imc', nome: 'IMC e faixa de peso', cat: 'cálculo',
    ícone: 'pessoas', tarefas: ['calcular'], status: 'planejada',
    resumo: 'Índice de massa corporal, faixa de referência e peso correspondente à faixa.',
    problema: 'Situar o peso em relação à altura com a referência adulta da OMS.',
    entra: 'Peso e altura.', processa: 'Calcula peso ÷ altura² e localiza a faixa.',
    sai: 'IMC, faixa e intervalo de peso da faixa saudável, com aviso de que não substitui avaliação profissional.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['imc', 'peso', 'altura'], intenções: ['calcular imc'],
  },
  {
    id: 'F046', slug: 'numeros-romanos', nome: 'Números romanos', cat: 'cálculo',
    ícone: 'texto', tarefas: ['converter'], status: 'planejada',
    resumo: 'Converte entre algarismos romanos e decimais, validando a grafia.',
    problema: 'Ler ou escrever um número romano sem errar a regra de subtração.',
    entra: 'Número decimal ou romano.', processa: 'Converte e valida a forma canônica.',
    sai: 'Número convertido.', exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['romano', 'algarismo'], intenções: ['converter número romano'],
  },
  {
    id: 'F047', slug: 'escala-e-proporcao', nome: 'Escala e proporção', cat: 'cálculo',
    ícone: 'régua', tarefas: ['calcular'], status: 'planejada',
    resumo: 'Redimensiona medidas mantendo proporção e converte escalas de planta.',
    problema: 'Redimensionar sem distorcer e ler medidas de uma planta em escala.',
    entra: 'Medidas originais, medida desejada ou escala.',
    processa: 'Aplica o fator de proporção a todas as medidas.',
    sai: 'Medidas finais e o fator aplicado.', exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['escala', 'proporção', 'planta'], intenções: ['redimensionar mantendo proporção'],
  },
  {
    id: 'F048', slug: 'calendario-do-mes', nome: 'Calendário para imprimir', cat: 'datas',
    ícone: 'datas', tarefas: ['criar', 'exportar'], status: 'planejada',
    resumo: 'Calendário mensal ou anual com feriados e espaço para anotações, em PDF.',
    problema: 'Ter um calendário na parede com os feriados certos.',
    entra: 'Ano, meses e feriados.', processa: 'Monta a grade do mês em A4.',
    sai: 'Calendário em PDF pronto para imprimir.', exporta: ['pdf', 'imprimir'], plano: 'gratuito', local: true,
    tags: ['calendário', 'imprimir', 'feriados'], intenções: ['calendário para imprimir'],
  },
  {
    id: 'F049', slug: 'contagem-regressiva', nome: 'Contagem regressiva', cat: 'datas',
    ícone: 'relógio', tarefas: ['organizar'], status: 'planejada',
    resumo: 'Acompanha quanto falta para uma data importante, com link para compartilhar.',
    problema: 'Acompanhar um prazo sem ficar contando no calendário.',
    entra: 'Data e título do evento.', processa: 'Atualiza a diferença em tempo real.',
    sai: 'Tempo restante e link compartilhável.', exporta: ['link'], plano: 'gratuito', local: true,
    tags: ['contagem regressiva', 'prazo'], intenções: ['quanto falta para a data'],
  },
  {
    id: 'F050', slug: 'fuso-horario', nome: 'Fuso horário e reunião', cat: 'datas',
    ícone: 'relógio', tarefas: ['converter'], status: 'planejada',
    resumo: 'Compara horários entre cidades e sugere janelas comuns para reunião.',
    problema: 'Marcar reunião com gente em outro fuso sem errar a hora.',
    entra: 'Cidades e faixa de horário aceitável.',
    processa: 'Converte pelos fusos do navegador e cruza as faixas.',
    sai: 'Horários equivalentes e janelas comuns.', exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['fuso', 'reunião', 'horário'], intenções: ['que horas são lá'],
  },
];
