/**
 * Catálogo — Dinheiro e preços, Vendas e propostas.
 * `status: 'pronta'` só para ferramenta que abre, valida, calcula, exporta e tem teste.
 */
export const ferramentas = [
  {
    id: 'F001', slug: 'porcentagem', nome: 'Calculadora de porcentagem', cat: 'cálculo',
    ícone: 'cálculo', tarefas: ['calcular'], status: 'pronta',
    resumo: 'Porcentagem de um valor, aumento, desconto, diferença percentual e quanto A é de B.',
    problema: 'Resolver qualquer conta de porcentagem sem precisar lembrar a fórmula certa.',
    entra: 'Dois números e a operação desejada.',
    processa: 'Aplica a fórmula da operação escolhida e mostra a conta feita.',
    sai: 'Resultado, valor da diferença e a fórmula usada.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    unifica: ['Porcentagem simples', 'Calculadora de desconto', 'Calculadora de acréscimo', 'Diferença percentual'],
    tags: ['porcentagem', 'desconto', 'aumento', 'acréscimo', 'variação'],
    intenções: ['calcular desconto', 'quanto por cento de aumento', 'quanto é 15% de um valor', 'diferença percentual entre dois valores'],
  },
  {
    id: 'F002', slug: 'preco-de-venda', nome: 'Preço de venda', cat: 'dinheiro',
    ícone: 'dinheiro', tarefas: ['calcular'], status: 'pronta',
    resumo: 'Preço a partir do custo, com margem sobre a venda, markup, taxas e impostos.',
    problema: 'Descobrir por quanto vender sem comer a própria margem com taxa de cartão e imposto.',
    entra: 'Custo, margem desejada, taxas percentuais, imposto e despesa fixa por unidade.',
    processa: 'Preço = (custo + fixo) ÷ (1 − margem − taxas − imposto), com aviso quando a soma passa de 100%.',
    sai: 'Preço sugerido, lucro por unidade, markup equivalente e composição do preço.',
    exporta: ['copiar', 'pdf'], plano: 'gratuito', local: true,
    unifica: ['Markup', 'Margem de lucro', 'Preço mínimo', 'Formação de preço'],
    tags: ['preço', 'margem', 'markup', 'lucro', 'taxa', 'imposto'],
    intenções: ['por quanto devo vender', 'calcular margem de lucro', 'formar preço de venda', 'markup'],
  },
  {
    id: 'F003', slug: 'juros', nome: 'Calculadora de juros', cat: 'dinheiro',
    ícone: 'gráfico', tarefas: ['calcular'], status: 'pronta',
    resumo: 'Juros simples e compostos, com aportes mensais e tabela período a período.',
    problema: 'Saber quanto um valor rende ou custa ao longo do tempo, com ou sem aportes.',
    entra: 'Valor inicial, taxa, período, tipo de juros e aporte mensal opcional.',
    processa: 'Aplica juros simples ou compostos e acumula os aportes no fim de cada período.',
    sai: 'Montante, total de juros, total aportado e tabela de evolução.',
    exporta: ['copiar', 'xlsx'], plano: 'gratuito', local: true,
    unifica: ['Juros simples', 'Juros compostos', 'Simulador de poupança', 'Valor futuro'],
    tags: ['juros', 'rendimento', 'investimento', 'poupança', 'montante'],
    intenções: ['quanto rende meu dinheiro', 'juros compostos', 'simular poupança', 'valor futuro'],
  },
  {
    id: 'F004', slug: 'parcelamento', nome: 'Simulador de parcelamento', cat: 'dinheiro',
    ícone: 'cálculo', tarefas: ['calcular', 'comparar'], status: 'pronta',
    resumo: 'Parcela pela Tabela Price, custo total do crédito e comparação com o pagamento à vista.',
    problema: 'Decidir entre pagar à vista com desconto ou parcelar, vendo o custo real.',
    entra: 'Valor, entrada, número de parcelas, taxa mensal e desconto à vista.',
    processa: 'Calcula a parcela pela Tabela Price e compara o total parcelado com o valor à vista.',
    sai: 'Parcela, total pago, juros embutidos e qual opção sai mais barata.',
    exporta: ['copiar', 'xlsx'], plano: 'gratuito', local: true,
    unifica: ['Tabela Price', 'Custo do parcelamento', 'À vista ou parcelado'],
    tags: ['parcela', 'financiamento', 'crediário', 'price', 'à vista'],
    intenções: ['vale a pena parcelar', 'calcular parcela', 'quanto fica por mês'],
  },
  {
    id: 'F005', slug: 'divisao-de-contas', nome: 'Divisão de contas', cat: 'dinheiro',
    ícone: 'pessoas', tarefas: ['calcular', 'organizar'], status: 'pronta',
    resumo: 'Quem pagou o quê, quanto cada um deve e o menor número de transferências para acertar.',
    problema: 'Acertar as contas de um grupo sem planilha e sem discussão.',
    entra: 'Participantes, o que cada um pagou e pesos opcionais.',
    processa: 'Soma os gastos, calcula o saldo de cada pessoa e reduz os acertos a transferências mínimas.',
    sai: 'Saldo por pessoa e lista de quem paga para quem.',
    exporta: ['copiar', 'pdf'], plano: 'gratuito', local: true,
    unifica: ['Divisor de despesas', 'Rateio proporcional', 'Vaquinha'],
    tags: ['rachar', 'dividir conta', 'rateio', 'despesas', 'viagem'],
    intenções: ['rachar a conta', 'dividir despesas da viagem', 'quem deve pra quem'],
  },
  {
    id: 'F006', slug: 'preco-por-unidade', nome: 'Preço por unidade', cat: 'dinheiro',
    ícone: 'caixa', tarefas: ['comparar'], status: 'pronta',
    resumo: 'Compara embalagens de tamanhos diferentes e mostra qual sai mais barata de verdade.',
    problema: 'Descobrir qual embalagem compensa quando os tamanhos e preços são diferentes.',
    entra: 'Preço, quantidade e unidade de cada embalagem.',
    processa: 'Converte tudo para a mesma unidade base e calcula o custo unitário.',
    sai: 'Custo por unidade de cada opção, a mais barata e a economia percentual.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    unifica: ['Comparador de embalagens', 'Preço proporcional', 'Custo por quilo'],
    tags: ['comparar preço', 'embalagem', 'custo por kg', 'litro', 'supermercado'],
    intenções: ['qual embalagem compensa', 'preço por quilo', 'comparar preços de embalagens'],
  },
  {
    id: 'F007', slug: 'numero-por-extenso', nome: 'Número por extenso', cat: 'dinheiro',
    ícone: 'texto', tarefas: ['converter'], status: 'pronta',
    resumo: 'Escreve números e valores em reais por extenso, para recibos e contratos.',
    problema: 'Escrever o valor por extenso sem errar centavos, plural e concordância.',
    entra: 'Um número, com a opção de tratar como dinheiro.',
    processa: 'Converte a parte inteira e os centavos para extenso em português do Brasil.',
    sai: 'Texto por extenso pronto para copiar.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    unifica: ['Valor por extenso', 'Número por extenso'],
    tags: ['extenso', 'recibo', 'cheque', 'contrato', 'reais'],
    intenções: ['escrever valor por extenso', 'número por extenso'],
  },
  {
    id: 'F008', slug: 'orcamento', nome: 'Orçamento e proposta', cat: 'vendas',
    ícone: 'documento', tarefas: ['criar', 'exportar'], status: 'pronta',
    resumo: 'Monta o orçamento com itens, desconto e validade; exporta PDF, planilha e link para o cliente.',
    problema: 'Enviar um orçamento apresentável sem abrir editor de texto nem planilha.',
    entra: 'Dados do emissor, do cliente, itens com quantidade e preço, desconto e condições.',
    processa: 'Calcula subtotal, desconto e total; monta o documento com a identidade do portal.',
    sai: 'Orçamento pronto, PDF, planilha .xlsx e link compartilhável.',
    exporta: ['pdf', 'xlsx', 'link', 'imprimir'], plano: 'gratuito', local: true,
    unifica: ['Orçamento de doces', 'Orçamento artesanal', 'Orçamento de festa', 'Orçamento de reforma', 'Proposta comercial'],
    tags: ['orçamento', 'proposta', 'cliente', 'pdf', 'excel'],
    intenções: ['fazer um orçamento', 'mandar proposta para o cliente', 'orçamento em pdf'],
  },
  {
    id: 'F009', slug: 'recibo', nome: 'Gerador de recibo', cat: 'documentos',
    ícone: 'documento', tarefas: ['criar', 'exportar'], status: 'pronta',
    resumo: 'Recibo de pagamento com valor por extenso, dados das partes e PDF pronto para assinar.',
    problema: 'Emitir um recibo correto sem modelo do Word.',
    entra: 'Quem recebeu, quem pagou, valor, referência, cidade e data.',
    processa: 'Valida os dados, escreve o valor por extenso e monta o documento em A4.',
    sai: 'Recibo em PDF com linha de assinatura e segunda via opcional.',
    exporta: ['pdf', 'imprimir'], plano: 'gratuito', local: true,
    unifica: ['Recibo de pagamento', 'Recibo de aluguel'],
    tags: ['recibo', 'pagamento', 'comprovante', 'assinatura'],
    intenções: ['fazer um recibo', 'comprovante de pagamento'],
  },
  {
    id: 'F010', slug: 'comissao', nome: 'Calculadora de comissão', cat: 'vendas',
    ícone: 'vendas', tarefas: ['calcular'], status: 'planejada',
    resumo: 'Comissão simples, escalonada por faixa de meta e comissão líquida após descontos.',
    problema: 'Calcular a comissão certa quando existem faixas e descontos.',
    entra: 'Vendas do período, faixas de comissão e descontos.',
    processa: 'Aplica a faixa correspondente a cada parte do valor e abate os descontos.',
    sai: 'Comissão bruta, descontos e comissão líquida por vendedor.',
    exporta: ['copiar', 'xlsx'], plano: 'gratuito', local: true,
    tags: ['comissão', 'vendedor', 'meta'], intenções: ['calcular comissão', 'comissão escalonada'],
  },
  {
    id: 'F011', slug: 'ponto-de-equilibrio', nome: 'Ponto de equilíbrio', cat: 'dinheiro',
    ícone: 'alvo', tarefas: ['calcular'], status: 'planejada',
    resumo: 'Quanto precisa vender para cobrir os custos, em valor e em quantidade.',
    problema: 'Saber a partir de qual faturamento o negócio começa a dar lucro.',
    entra: 'Custos fixos, custo variável unitário e preço de venda.',
    processa: 'Calcula a margem de contribuição e divide os custos fixos por ela.',
    sai: 'Ponto de equilíbrio em unidades e em reais, com margem de contribuição.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['ponto de equilíbrio', 'break even', 'margem de contribuição'],
    intenções: ['quanto preciso vender para pagar as despesas'],
  },
  {
    id: 'F012', slug: 'fluxo-de-caixa', nome: 'Fluxo de caixa', cat: 'dinheiro',
    ícone: 'gráfico', tarefas: ['organizar', 'analisar'], status: 'planejada',
    resumo: 'Entradas e saídas por período, saldo acumulado e projeção simples.',
    problema: 'Enxergar quando o caixa fica negativo antes de acontecer.',
    entra: 'Lançamentos com data, descrição, tipo e valor.',
    processa: 'Agrupa por período e acumula o saldo.',
    sai: 'Saldo por período, saldo acumulado e alerta de caixa negativo.',
    exporta: ['xlsx', 'pdf'], plano: 'gratuito', local: true,
    tags: ['fluxo de caixa', 'contas a pagar', 'contas a receber'],
    intenções: ['organizar meu caixa', 'quando vou ficar no vermelho'],
  },
  {
    id: 'F013', slug: 'conversor-de-moedas', nome: 'Conversor de moedas', cat: 'dinheiro',
    ícone: 'dinheiro', tarefas: ['converter'], status: 'planejada',
    resumo: 'Converte valores entre moedas com a cotação informada por você.',
    problema: 'Converter valores sem depender de cotação inventada pelo site.',
    entra: 'Valor, moeda de origem, moeda de destino e cotação.',
    processa: 'Multiplica pela cotação informada e registra a data da referência.',
    sai: 'Valor convertido com a cotação e a data usadas.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['moeda', 'dólar', 'euro', 'câmbio'], intenções: ['converter dólar para real'],
  },
  {
    id: 'F014', slug: 'roi-e-metricas', nome: 'ROI, ROAS, CAC e LTV', cat: 'marketing',
    ícone: 'alvo', tarefas: ['calcular'], status: 'planejada',
    resumo: 'Retorno de investimento, retorno de anúncio, custo de aquisição e valor do cliente.',
    problema: 'Saber se a campanha ou o investimento realmente se paga.',
    entra: 'Investimento, receita, número de clientes e ticket médio.',
    processa: 'Aplica cada fórmula e mostra as premissas assumidas.',
    sai: 'ROI, ROAS, CAC, LTV e relação LTV/CAC.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['roi', 'roas', 'cac', 'ltv', 'campanha'], intenções: ['a campanha deu retorno'],
  },
  {
    id: 'F015', slug: 'rateio-de-custos', nome: 'Rateio de custos', cat: 'dinheiro',
    ícone: 'filtro', tarefas: ['calcular'], status: 'planejada',
    resumo: 'Distribui um custo comum entre setores, produtos ou pessoas por critério escolhido.',
    problema: 'Dividir um custo compartilhado de forma justa e defensável.',
    entra: 'Valor total, itens e o peso de cada um.',
    processa: 'Distribui proporcionalmente ao peso e trata o arredondamento do último item.',
    sai: 'Valor rateado por item, com total conferido.',
    exporta: ['copiar', 'xlsx'], plano: 'gratuito', local: true,
    tags: ['rateio', 'custo indireto', 'proporcional'], intenções: ['dividir custo entre setores'],
  },
  {
    id: 'F016', slug: 'pedido-de-venda', nome: 'Pedido de venda', cat: 'vendas',
    ícone: 'lista', tarefas: ['criar', 'exportar'], status: 'planejada',
    resumo: 'Pedido com itens, condições e prazo de entrega, pronto para PDF.',
    problema: 'Registrar o pedido do cliente sem sistema de gestão.',
    entra: 'Cliente, itens, condição de pagamento e prazo.',
    processa: 'Calcula totais e numera o pedido.',
    sai: 'Pedido em PDF e planilha.',
    exporta: ['pdf', 'xlsx'], plano: 'gratuito', local: true,
    tags: ['pedido', 'venda'], intenções: ['registrar pedido do cliente'],
  },
  {
    id: 'F017', slug: 'ficha-de-cliente', nome: 'Ficha de cliente', cat: 'vendas',
    ícone: 'pessoas', tarefas: ['organizar'], status: 'planejada',
    resumo: 'Cadastro simples de clientes salvo no próprio aparelho, com busca e exportação.',
    problema: 'Guardar contatos e histórico sem contratar um CRM.',
    entra: 'Nome, contato, observações e histórico de compras.',
    processa: 'Salva localmente com validação e permite exportar cópia.',
    sai: 'Lista pesquisável e arquivo de backup.',
    exporta: ['xlsx', 'json'], plano: 'gratuito', local: true,
    tags: ['cliente', 'cadastro', 'crm'], intenções: ['guardar meus clientes'],
  },
  {
    id: 'F018', slug: 'follow-up', nome: 'Mensagem de follow-up', cat: 'vendas',
    ícone: 'balão', tarefas: ['criar'], status: 'planejada',
    resumo: 'Monta a mensagem de retomada de contato a partir do contexto da negociação.',
    problema: 'Escrever a cobrança educada de resposta sem soar insistente.',
    entra: 'Cliente, assunto, data do último contato e tom desejado.',
    processa: 'Preenche um modelo revisado com os dados informados.',
    sai: 'Mensagem pronta para copiar.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['follow-up', 'retomar contato'], intenções: ['cliente sumiu o que escrevo'],
  },
  {
    id: 'F019', slug: 'meta-de-faturamento', nome: 'Meta de faturamento', cat: 'vendas',
    ícone: 'alvo', tarefas: ['calcular'], status: 'planejada',
    resumo: 'Quanto vender por dia, semana e vendedor para bater a meta do mês.',
    problema: 'Transformar a meta do mês em um número diário possível de acompanhar.',
    entra: 'Meta, dias úteis, ticket médio e número de vendedores.',
    processa: 'Divide a meta pelos dias e pessoas e estima o número de vendas.',
    sai: 'Meta diária, semanal, por vendedor e número de vendas necessárias.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['meta', 'faturamento'], intenções: ['quanto preciso vender por dia'],
  },
  {
    id: 'F020', slug: 'ticket-medio', nome: 'Ticket médio e conversão', cat: 'vendas',
    ícone: 'gráfico', tarefas: ['calcular'], status: 'planejada',
    resumo: 'Ticket médio, taxa de conversão e o efeito de melhorar cada um deles.',
    problema: 'Descobrir se compensa mais vender para mais gente ou vender mais por pessoa.',
    entra: 'Faturamento, número de vendas e número de atendimentos.',
    processa: 'Calcula os indicadores e simula cenários de melhoria.',
    sai: 'Ticket médio, conversão e simulação de ganho.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['ticket médio', 'conversão'], intenções: ['melhorar minhas vendas'],
  },
];
