/** Catálogo — RH e trabalho, Estoque e logística, Produtividade, Vendas. */
export const ferramentas = [
  {
    id: 'F085', slug: 'ferias', nome: 'Cálculo de férias', cat: 'trabalho',
    ícone: 'dinheiro', tarefas: ['calcular'], status: 'planejada',
    resumo: 'Calcula o valor das férias com um terço constitucional e o abono pecuniário.',
    problema: 'Conferir se o valor das férias recebido está correto.',
    entra: 'Salário, dias de férias e se vai vender parte delas (abono).',
    processa: 'Calcula o valor proporcional aos dias, soma um terço e o abono quando marcado.',
    sai: 'Valor das férias, um terço constitucional e valor do abono.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['férias', 'abono pecuniário', 'um terço'],
    intenções: ['calcular valor das férias', 'quanto vou receber de férias'],
  },
  {
    id: 'F086', slug: 'rescisao-estimada', nome: 'Estimativa de rescisão', cat: 'trabalho',
    ícone: 'dinheiro', tarefas: ['calcular'], status: 'planejada',
    resumo: 'Estima o valor da rescisão por tipo de desligamento, com aviso, férias e décimo terceiro.',
    problema: 'Ter uma ideia do valor da rescisão antes de receber o cálculo oficial.',
    entra: 'Salário, tempo de casa, tipo de desligamento e saldo de férias.',
    processa: 'Soma saldo de salário, aviso prévio, férias proporcionais e décimo terceiro conforme o tipo de rescisão.',
    sai: 'Estimativa detalhada por verba, com aviso de que o valor oficial cabe ao RH.',
    exporta: ['copiar', 'pdf'], plano: 'gratuito', local: true,
    tags: ['rescisão', 'demissão', 'aviso prévio'],
    intenções: ['quanto vou receber de rescisão'],
  },
  {
    id: 'F087', slug: 'salario-liquido-estimado', nome: 'Salário líquido estimado', cat: 'trabalho',
    ícone: 'dinheiro', tarefas: ['calcular'], status: 'planejada',
    resumo: 'Estima o salário líquido a partir do bruto, descontando INSS e IRRF pela tabela vigente.',
    problema: 'Saber quanto cai na conta antes de fechar a proposta de emprego.',
    entra: 'Salário bruto, dependentes e outros descontos.',
    processa: 'Aplica as faixas de INSS e IRRF em vigor e desconta os valores informados.',
    sai: 'Salário líquido estimado e o detalhamento dos descontos.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['salário líquido', 'inss', 'irrf', 'holerite'],
    intenções: ['quanto sobra do salário depois do desconto'],
  },
  {
    id: 'F088', slug: 'escala-de-trabalho', nome: 'Escala de trabalho', cat: 'trabalho',
    ícone: 'pessoas', tarefas: ['organizar'], status: 'planejada',
    resumo: 'Monta a escala da equipe por turno e folga, incluindo padrões como 12x36 e 6x1.',
    problema: 'Organizar quem trabalha em cada dia sem esquecer ninguém nem deixar buraco.',
    entra: 'Equipe, padrão de escala e período.',
    processa: 'Distribui os turnos e folgas conforme o padrão escolhido.',
    sai: 'Escala do período por pessoa e por dia.',
    exporta: ['xlsx', 'pdf'], plano: 'gratuito', local: true,
    tags: ['escala', 'turno', '12x36', 'folga'],
    intenções: ['montar escala de trabalho da equipe'],
  },
  {
    id: 'F089', slug: 'avaliacao-de-desempenho', nome: 'Avaliação de desempenho', cat: 'trabalho',
    ícone: 'pessoas', tarefas: ['criar'], status: 'planejada',
    resumo: 'Monta um formulário de avaliação por competências com nota e comentário.',
    problema: 'Avaliar a equipe de forma organizada em vez de uma conversa solta.',
    entra: 'Competências avaliadas, notas e comentários.',
    processa: 'Organiza as competências, calcula a média e monta o relatório.',
    sai: 'Avaliação preenchida em PDF, com média por competência.',
    exporta: ['pdf'], plano: 'gratuito', local: true,
    tags: ['avaliação de desempenho', 'competências', 'feedback'],
    intenções: ['fazer avaliação de desempenho do funcionário'],
  },
  {
    id: 'F090', slug: 'descricao-de-vaga', nome: 'Descrição de vaga', cat: 'trabalho',
    ícone: 'documento', tarefas: ['criar'], status: 'planejada',
    resumo: 'Monta o anúncio da vaga com responsabilidades, requisitos e benefícios.',
    problema: 'Publicar uma vaga completa sem esquecer nenhuma seção importante.',
    entra: 'Cargo, responsabilidades, requisitos, benefícios e forma de candidatura.',
    processa: 'Organiza as seções no formato padrão de anúncio de vaga.',
    sai: 'Texto da vaga pronto para publicar.',
    exporta: ['copiar', 'pdf'], plano: 'gratuito', local: true,
    tags: ['vaga', 'anúncio de emprego', 'recrutamento'],
    intenções: ['escrever descrição de vaga'],
  },
  {
    id: 'F091', slug: 'roteiro-de-entrevista', nome: 'Roteiro de entrevista', cat: 'trabalho',
    ícone: 'pessoas', tarefas: ['criar'], status: 'planejada',
    resumo: 'Monta o roteiro de perguntas da entrevista por competência avaliada.',
    problema: 'Conduzir entrevistas parecidas para poder comparar os candidatos depois.',
    entra: 'Cargo e competências a avaliar.',
    processa: 'Sugere perguntas por competência e organiza o roteiro.',
    sai: 'Roteiro de entrevista em PDF, com espaço para anotar as respostas.',
    exporta: ['pdf', 'imprimir'], plano: 'gratuito', local: true,
    tags: ['entrevista', 'roteiro', 'recrutamento'],
    intenções: ['roteiro de perguntas para entrevista'],
  },
  {
    id: 'F092', slug: 'plano-de-onboarding', nome: 'Plano de onboarding', cat: 'trabalho',
    ícone: 'lista', tarefas: ['organizar'], status: 'planejada',
    resumo: 'Monta o cronograma dos primeiros dias de um novo funcionário, por etapa e responsável.',
    problema: 'Receber um novo funcionário sem improvisar o primeiro dia.',
    entra: 'Cargo, data de início e as etapas de integração.',
    processa: 'Organiza as etapas por dia e responsável.',
    sai: 'Plano de onboarding em PDF ou planilha.',
    exporta: ['pdf', 'xlsx'], plano: 'gratuito', local: true,
    tags: ['onboarding', 'integração', 'novo funcionário'],
    intenções: ['planejar integração de novo funcionário'],
  },
  {
    id: 'F093', slug: 'organograma', nome: 'Gerador de organograma', cat: 'trabalho',
    ícone: 'pessoas', tarefas: ['criar'], status: 'planejada',
    resumo: 'Monta o organograma da equipe a partir dos cargos e das relações de hierarquia.',
    problema: 'Visualizar quem responde para quem sem desenhar no papel.',
    entra: 'Cargos e a quem cada um responde.',
    processa: 'Monta a árvore hierárquica a partir das relações informadas.',
    sai: 'Organograma em imagem e PDF.',
    exporta: ['png', 'pdf'], plano: 'gratuito', local: true,
    tags: ['organograma', 'hierarquia', 'estrutura'],
    intenções: ['montar organograma da empresa'],
  },
  {
    id: 'F094', slug: 'estoque-minimo', nome: 'Estoque mínimo e de segurança', cat: 'operações',
    ícone: 'caixa', tarefas: ['calcular'], status: 'planejada',
    resumo: 'Calcula o estoque mínimo e de segurança a partir do consumo e do prazo de reposição.',
    problema: 'Saber a partir de quantas unidades é hora de repor, sem faltar nem sobrar.',
    entra: 'Consumo médio, prazo de reposição e variação da demanda.',
    processa: 'Aplica a fórmula de estoque mínimo com margem de segurança sobre a variação.',
    sai: 'Estoque mínimo, estoque de segurança e ponto de atenção.',
    exporta: ['copiar', 'xlsx'], plano: 'gratuito', local: true,
    tags: ['estoque mínimo', 'estoque de segurança'],
    intenções: ['calcular estoque mínimo'],
  },
  {
    id: 'F095', slug: 'ponto-de-reposicao', nome: 'Ponto de reposição', cat: 'operações',
    ícone: 'caixa', tarefas: ['calcular'], status: 'planejada',
    resumo: 'Calcula em qual quantidade fazer o novo pedido para não zerar o estoque.',
    problema: 'Saber a hora certa de repor sem esperar o produto acabar.',
    entra: 'Consumo médio diário, prazo de entrega do fornecedor e estoque de segurança.',
    processa: 'Multiplica o consumo médio pelo prazo de entrega e soma o estoque de segurança.',
    sai: 'Ponto de reposição em unidades.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['ponto de reposição', 'pedido de compra'],
    intenções: ['quando fazer o próximo pedido de estoque'],
  },
  {
    id: 'F096', slug: 'giro-de-estoque', nome: 'Giro de estoque', cat: 'operações',
    ícone: 'gráfico', tarefas: ['calcular', 'analisar'], status: 'planejada',
    resumo: 'Calcula quantas vezes o estoque girou no período e o tempo médio de permanência.',
    problema: 'Saber se o dinheiro parado em estoque está girando rápido o suficiente.',
    entra: 'Custo das vendas do período e estoque médio.',
    processa: 'Divide o custo das vendas pelo estoque médio e converte em dias.',
    sai: 'Giro de estoque no período e dias médios de estoque.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['giro de estoque', 'estoque médio'],
    intenções: ['calcular giro de estoque'],
  },
  {
    id: 'F097', slug: 'curva-abc', nome: 'Curva ABC de produtos', cat: 'operações',
    ícone: 'gráfico', tarefas: ['analisar'], status: 'planejada',
    resumo: 'Classifica os produtos em A, B e C pela participação no faturamento ou saída.',
    problema: 'Descobrir quais produtos merecem mais atenção no estoque e nas compras.',
    entra: 'Lista de produtos com valor ou quantidade vendida.',
    processa: 'Ordena do maior para o menor, acumula o percentual e classifica pelas faixas ABC.',
    sai: 'Lista classificada em A, B e C, com o percentual acumulado.',
    exporta: ['xlsx', 'csv'], plano: 'gratuito', local: true,
    tags: ['curva abc', 'classificação de produtos'],
    intenções: ['fazer curva abc dos produtos'],
  },
  {
    id: 'F098', slug: 'cubagem', nome: 'Cálculo de cubagem', cat: 'operações',
    ícone: 'caixa', tarefas: ['calcular'], status: 'planejada',
    resumo: 'Calcula o volume ocupado por uma carga a partir das medidas de cada volume.',
    problema: 'Saber quanto espaço uma carga vai ocupar no veículo ou contêiner.',
    entra: 'Comprimento, largura, altura e quantidade de cada volume.',
    processa: 'Multiplica as três dimensões e soma o volume de todos os volumes.',
    sai: 'Cubagem total em metros cúbicos.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['cubagem', 'volume de carga', 'm³'],
    intenções: ['calcular cubagem da carga'],
  },
  {
    id: 'F099', slug: 'peso-volumetrico', nome: 'Peso volumétrico', cat: 'operações',
    ícone: 'caixa', tarefas: ['calcular', 'comparar'], status: 'planejada',
    resumo: 'Calcula o peso cubado de um volume e compara com o peso real para o frete.',
    problema: 'Entender por que a transportadora cobrou pelo peso cubado e não pelo peso real.',
    entra: 'Medidas do volume, peso real e fator de cubagem da transportadora.',
    processa: 'Calcula o peso volumétrico e usa o maior entre ele e o peso real.',
    sai: 'Peso volumétrico, peso real e o peso considerado para cobrança.',
    exporta: ['copiar'], plano: 'gratuito', local: true,
    tags: ['peso volumétrico', 'peso cubado', 'frete'],
    intenções: ['calcular peso cubado do frete'],
  },
  {
    id: 'F100', slug: 'romaneio', nome: 'Romaneio de carga', cat: 'operações',
    ícone: 'documento', tarefas: ['criar', 'exportar'], status: 'planejada',
    resumo: 'Monta o romaneio com os volumes, pesos e destinatários de uma expedição.',
    problema: 'Documentar o que está sendo enviado numa carga com vários volumes.',
    entra: 'Volumes, conteúdo, peso de cada um e destinatário.',
    processa: 'Organiza os volumes em lista numerada com os totais.',
    sai: 'Romaneio em PDF pronto para acompanhar a carga.',
    exporta: ['pdf', 'xlsx'], plano: 'gratuito', local: true,
    tags: ['romaneio', 'expedição', 'carga'],
    intenções: ['fazer romaneio de carga'],
  },
  {
    id: 'F101', slug: 'etiqueta-de-expedicao', nome: 'Etiqueta de expedição', cat: 'operações',
    ícone: 'grade', tarefas: ['criar', 'exportar'], status: 'planejada',
    resumo: 'Gera etiquetas de volume com remetente, destinatário e numeração da carga.',
    problema: 'Identificar cada volume de uma expedição com informação legível.',
    entra: 'Dados do remetente, do destinatário e a numeração dos volumes.',
    processa: 'Monta uma etiqueta por volume, numerada em sequência.',
    sai: 'Etiquetas em PDF, uma por volume, prontas para imprimir e colar.',
    exporta: ['pdf', 'imprimir'], plano: 'gratuito', local: true,
    tags: ['etiqueta de expedição', 'volume', 'transporte'],
    intenções: ['gerar etiqueta para a caixa da entrega'],
  },
  {
    id: 'F102', slug: 'conferencia-de-pedido', nome: 'Conferência de pedido', cat: 'operações',
    ícone: 'confere-círculo', tarefas: ['validar', 'organizar'], status: 'planejada',
    resumo: 'Confere os itens separados contra a lista do pedido e aponta o que falta ou sobra.',
    problema: 'Evitar que um pedido saia errado da separação.',
    entra: 'Lista do pedido e os itens conferidos na separação.',
    processa: 'Casa os itens pela referência e aponta diferenças de quantidade.',
    sai: 'Lista de itens conferidos, faltantes e excedentes.',
    exporta: ['csv', 'copiar'], plano: 'gratuito', local: true,
    tags: ['conferência', 'separação de pedido', 'picking'],
    intenções: ['conferir pedido antes de despachar'],
  },
  {
    id: 'F103', slug: 'calculadora-de-frete', nome: 'Calculadora de frete', cat: 'operações',
    ícone: 'caixa', tarefas: ['calcular', 'comparar'], status: 'planejada',
    resumo: 'Estima o frete por peso, cubagem e distância, e compara transportadoras.',
    problema: 'Comparar propostas de frete diferentes antes de fechar com uma transportadora.',
    entra: 'Peso, medidas, distância e a tabela de cada transportadora.',
    processa: 'Calcula o peso considerado e aplica a tabela de cada opção.',
    sai: 'Valor estimado por transportadora e a mais barata.',
    exporta: ['copiar', 'xlsx'], plano: 'gratuito', local: true,
    tags: ['frete', 'transportadora', 'cotação de frete'],
    intenções: ['comparar frete de transportadoras'],
  },
  {
    id: 'F104', slug: 'lista-de-tarefas', nome: 'Lista de tarefas', cat: 'produtividade',
    ícone: 'lista', tarefas: ['organizar'], status: 'planejada',
    resumo: 'Organiza tarefas por prioridade e prazo, com marcação de concluído.',
    problema: 'Ter uma lista de tarefas simples sem instalar um aplicativo.',
    entra: 'Tarefas, prioridade e prazo de cada uma.',
    processa: 'Ordena pela prioridade e prazo escolhidos.',
    sai: 'Lista organizada, salva no aparelho.',
    exporta: ['copiar', 'json'], plano: 'gratuito', local: true,
    tags: ['lista de tarefas', 'to-do', 'prioridade'],
    intenções: ['organizar minhas tarefas do dia'],
  },
  {
    id: 'F105', slug: 'quadro-kanban', nome: 'Quadro Kanban', cat: 'produtividade',
    ícone: 'grade', tarefas: ['organizar'], status: 'planejada',
    resumo: 'Organiza tarefas em colunas de a fazer, fazendo e feito, com arrastar e soltar.',
    problema: 'Ver o andamento de várias tarefas de um jeito visual.',
    entra: 'Tarefas e a coluna de cada uma.',
    processa: 'Mantém o quadro salvo no aparelho e atualiza ao mover os cartões.',
    sai: 'Quadro Kanban salvo, exportável em imagem.',
    exporta: ['png', 'json'], plano: 'gratuito', local: true,
    tags: ['kanban', 'quadro de tarefas', 'andamento'],
    intenções: ['montar um quadro kanban'],
  },
  {
    id: 'F106', slug: 'matriz-eisenhower', nome: 'Matriz de Eisenhower', cat: 'produtividade',
    ícone: 'grade', tarefas: ['organizar', 'analisar'], status: 'planejada',
    resumo: 'Separa as tarefas em urgente, importante, nenhum dos dois ou ambos.',
    problema: 'Decidir o que fazer primeiro quando tudo parece urgente.',
    entra: 'Lista de tarefas.',
    processa: 'Classifica cada tarefa nos quatro quadrantes conforme urgência e importância.',
    sai: 'Matriz com as tarefas distribuídas nos quatro quadrantes.',
    exporta: ['png', 'pdf'], plano: 'gratuito', local: true,
    tags: ['matriz de eisenhower', 'prioridade', 'urgente e importante'],
    intenções: ['priorizar tarefas urgentes e importantes'],
  },
  {
    id: 'F107', slug: 'matriz-5w2h', nome: 'Plano de ação 5W2H', cat: 'produtividade',
    ícone: 'lista', tarefas: ['criar', 'organizar'], status: 'planejada',
    resumo: 'Organiza a ação em o quê, por quê, quem, quando, onde, como e quanto custa.',
    problema: 'Planejar uma ação sem esquecer nenhuma pergunta importante.',
    entra: 'Respostas para cada uma das sete perguntas.',
    processa: 'Organiza as respostas na estrutura 5W2H.',
    sai: 'Plano de ação em PDF ou planilha.',
    exporta: ['pdf', 'xlsx'], plano: 'gratuito', local: true,
    tags: ['5w2h', 'plano de ação'],
    intenções: ['montar plano de ação 5w2h'],
  },
  {
    id: 'F108', slug: 'plano-de-acao', nome: 'Plano de ação com responsáveis', cat: 'produtividade',
    ícone: 'lista', tarefas: ['organizar'], status: 'planejada',
    resumo: 'Lista ações, responsáveis e prazos, com acompanhamento de status.',
    problema: 'Transformar uma reunião de decisões em ações com dono e prazo.',
    entra: 'Ações, responsável, prazo e status de cada uma.',
    processa: 'Organiza a lista e sinaliza os prazos vencidos.',
    sai: 'Plano de ação em planilha ou PDF.',
    exporta: ['xlsx', 'pdf'], plano: 'gratuito', local: true,
    tags: ['plano de ação', 'responsáveis', 'prazo'],
    intenções: ['organizar ações e responsáveis da reunião'],
  },
  {
    id: 'F109', slug: 'ata-de-reuniao', nome: 'Ata de reunião', cat: 'produtividade',
    ícone: 'documento', tarefas: ['criar', 'exportar'], status: 'planejada',
    resumo: 'Registra pauta, presentes, decisões e ações combinadas numa reunião.',
    problema: 'Documentar o que foi decidido numa reunião sem perder detalhes depois.',
    entra: 'Data, presentes, pauta, decisões e ações combinadas.',
    processa: 'Organiza as informações no formato padrão de ata.',
    sai: 'Ata em PDF pronta para compartilhar com os participantes.',
    exporta: ['pdf', 'copiar'], plano: 'gratuito', local: true,
    tags: ['ata de reunião', 'decisões', 'registro'],
    intenções: ['fazer a ata da reunião'],
  },
  {
    id: 'F110', slug: 'pauta-de-reuniao', nome: 'Pauta de reunião', cat: 'produtividade',
    ícone: 'lista', tarefas: ['criar', 'organizar'], status: 'planejada',
    resumo: 'Organiza os assuntos da reunião com tempo estimado para cada um.',
    problema: 'Fazer uma reunião não passar do tempo por falta de roteiro.',
    entra: 'Assuntos, responsável e tempo estimado de cada um.',
    processa: 'Soma o tempo total e organiza os assuntos em ordem.',
    sai: 'Pauta em PDF com o tempo total da reunião.',
    exporta: ['pdf', 'imprimir'], plano: 'gratuito', local: true,
    tags: ['pauta de reunião', 'roteiro', 'tempo de reunião'],
    intenções: ['montar pauta da reunião'],
  },
  {
    id: 'F111', slug: 'cronograma-de-projeto', nome: 'Cronograma de projeto', cat: 'produtividade',
    ícone: 'datas', tarefas: ['organizar'], status: 'planejada',
    resumo: 'Organiza as etapas de um projeto em uma linha do tempo com datas e responsáveis.',
    problema: 'Ver as etapas do projeto e os prazos de cada uma num só lugar.',
    entra: 'Etapas, data de início, duração e responsável.',
    processa: 'Distribui as etapas na linha do tempo e aponta sobreposições.',
    sai: 'Cronograma visual e em planilha.',
    exporta: ['xlsx', 'pdf'], plano: 'gratuito', local: true,
    tags: ['cronograma', 'projeto', 'linha do tempo'],
    intenções: ['montar cronograma do projeto'],
  },
  {
    id: 'F112', slug: 'matriz-de-risco', nome: 'Matriz de risco', cat: 'produtividade',
    ícone: 'alerta', tarefas: ['analisar', 'organizar'], status: 'planejada',
    resumo: 'Classifica riscos por probabilidade e impacto, numa grade de calor.',
    problema: 'Priorizar quais riscos do projeto merecem atenção primeiro.',
    entra: 'Riscos, probabilidade e impacto de cada um.',
    processa: 'Posiciona cada risco na grade e calcula a severidade.',
    sai: 'Matriz de risco visual e lista ordenada por severidade.',
    exporta: ['png', 'xlsx'], plano: 'gratuito', local: true,
    tags: ['matriz de risco', 'probabilidade e impacto'],
    intenções: ['montar matriz de risco do projeto'],
  },
  {
    id: 'F113', slug: 'matriz-raci', nome: 'Matriz RACI', cat: 'produtividade',
    ícone: 'grade', tarefas: ['organizar'], status: 'planejada',
    resumo: 'Define quem é responsável, aprovador, consultado e informado em cada atividade.',
    problema: 'Acabar com a confusão de quem faz o quê num projeto com várias pessoas.',
    entra: 'Atividades e o papel de cada pessoa em cada uma.',
    processa: 'Monta a tabela cruzando atividades e pessoas.',
    sai: 'Matriz RACI em planilha ou PDF.',
    exporta: ['xlsx', 'pdf'], plano: 'gratuito', local: true,
    tags: ['raci', 'responsabilidades', 'papéis do projeto'],
    intenções: ['montar matriz raci'],
  },
  {
    id: 'F114', slug: 'funil-de-vendas', nome: 'Funil de vendas', cat: 'vendas',
    ícone: 'filtro', tarefas: ['analisar', 'organizar'], status: 'planejada',
    resumo: 'Acompanha quantos leads passam por cada etapa até virar venda, com taxa de conversão.',
    problema: 'Ver em qual etapa o funil está perdendo mais gente.',
    entra: 'Número de leads em cada etapa do funil.',
    processa: 'Calcula a taxa de conversão entre uma etapa e a seguinte.',
    sai: 'Funil visual com as taxas de conversão de cada etapa.',
    exporta: ['png', 'xlsx'], plano: 'gratuito', local: true,
    tags: ['funil de vendas', 'conversão', 'leads'],
    intenções: ['montar funil de vendas'],
  },
  {
    id: 'F115', slug: 'script-de-abordagem', nome: 'Script de abordagem', cat: 'vendas',
    ícone: 'balão', tarefas: ['criar'], status: 'planejada',
    resumo: 'Monta o roteiro de abordagem de vendas por etapa: contato, apresentação e fechamento.',
    problema: 'Ter um roteiro para não travar na hora de abordar o cliente.',
    entra: 'Produto, público e objeções comuns.',
    processa: 'Organiza o roteiro por etapa da conversa.',
    sai: 'Script pronto para copiar ou imprimir.',
    exporta: ['copiar', 'pdf'], plano: 'gratuito', local: true,
    tags: ['script de vendas', 'abordagem', 'objeções'],
    intenções: ['roteiro para abordar cliente'],
  },
  {
    id: 'F116', slug: 'calculadora-de-nps', nome: 'Calculadora de NPS', cat: 'vendas',
    ícone: 'gráfico', tarefas: ['calcular', 'analisar'], status: 'planejada',
    resumo: 'Calcula o Net Promoter Score a partir das notas de 0 a 10 dadas pelos clientes.',
    problema: 'Transformar as respostas da pesquisa de satisfação num número comparável.',
    entra: 'Lista de notas de 0 a 10.',
    processa: 'Classifica em detratores, neutros e promotores e calcula o NPS.',
    sai: 'NPS, percentual de cada grupo e classificação da zona.',
    exporta: ['copiar', 'xlsx'], plano: 'gratuito', local: true,
    tags: ['nps', 'satisfação do cliente', 'pesquisa'],
    intenções: ['calcular nps da pesquisa de satisfação'],
  },
  {
    id: 'F117', slug: 'previsao-de-vendas', nome: 'Previsão de vendas', cat: 'vendas',
    ícone: 'gráfico', tarefas: ['calcular', 'analisar'], status: 'planejada',
    resumo: 'Projeta as vendas dos próximos meses a partir do histórico e de uma taxa de crescimento.',
    problema: 'Ter uma estimativa de vendas futuras para planejar compra e caixa.',
    entra: 'Vendas dos últimos meses e taxa de crescimento esperada.',
    processa: 'Aplica a tendência do histórico e projeta os próximos períodos.',
    sai: 'Projeção mês a mês e gráfico de tendência.',
    exporta: ['xlsx', 'copiar'], plano: 'gratuito', local: true,
    tags: ['previsão de vendas', 'projeção', 'tendência'],
    intenções: ['prever vendas dos próximos meses'],
  },
];
